### ISSUE TITLE
addTaxonNames for plasmids returns : Error: Found bad taxon id (out of range error) in line: C	

### ISSUE THREAD

**Issue by mokrobial** [bioinformatics-centre/kaiju#102]
Hello, 

Steps:
1. installed kaiju
2. downloaded plasmid db from:  http://kaiju.binf.ku.dk/database/kaiju_db_plasmids_2019-02-05.tgz
3. created ref db and index
4. ran kaiju for input files using plasmid db 
5. verified output looked good
6. ran: addTaxonNames -u -t ~/kaiju/kaijudb/plasmid/nodes.dmp -n  ~/kaiju/kaijudb/plasmid/nodes.dmpnames.dmp -i kaiju-plasmid-out -o kaiju-plasmid-w-names

Result: "Error: Found bad taxon id (out of range error) in line: C	M02450:40:000000"
no file created 

// this awesome tool is awesome and worked GREAT w the viral db and it's the bees knees

**Comment by pmenzel** [comment]
Thanks, I will look into it.
It looks like your output file misses the third column with the taxon id, at least in this particular line.
Can you check this? Also, I just realized, that the nodes.dmp and names.dmp were not contained in the 2019-05-02 database files. Which dmp files did you use then?

**Comment by pmenzel** [comment]
I fixed the downloadable files, and the plasmid database and addTaxonNames works fine for me. So, if the problem persists on your side, I would need your fastq file to fully replicate and the kaiju command you used.

Also note that your step 3 is not necessary, you can directly use the .fmi file contained in the downloaded tgz file.
