### ISSUE TITLE
different results with and without -mem option

### ISSUE THREAD

**Issue by rderelle** [bioinformatics-centre/kaiju#105]
Hi,

I have noticed something really strange with Kaiju: I do not obtain the same results when running it without option and when running it with the '-mem' option.
For instance, using the proGenome database, one of my samples will have 170350 classified reads with the default command line and 173349 classified reads  with the '-mem' option. I have observed that same behaviour for all my samples.

It does not make any sense to me since the -mem option is enabled by default and the 2 command lines (with and without -mem option) should give the exact same result.
 
Perhaps an underlying parameter is activated when the -mem option is specified (?).

best,
Romain

**Comment by rderelle** [comment]
my apologies, I ment the '-a mem' option and not '-mem'.

**Comment by pmenzel** [comment]
Hi,

since version 1.6.0, the default run mode is `greedy` with 3 allowed mismatches. Unfortunately, I didn't change the sentence in the README file accordingly, until 3 days ago.
Therefore, when using `-a mem`, you switched the modes and got different results.
sorry for the trouble,
Peter

**Comment by rderelle** [comment]
Sorry, I haven't seen that change. Then it makes sense.
Many thanks for your reply.
