### ISSUE TITLE
Kaiju MEM : maximal length for each read

### ISSUE THREAD

**Issue by jfourquet2** [bioinformatics-centre/kaiju#107]
Hello,
When I run kaiju MEM with the verbose mode, I have maximal length in the 4th column. I have 2x150bp reads and the maximum of the maximal lengths is 50. We think that it is because it is the amino acids sequence length and 150/3 = 50. But surprisingly we have a lot of reads which have the maximal length between 49 and 50. Is there normal ?
Thanks in advance for your answer !

**Comment by pmenzel** [comment]
Good that you think about these things!
A MEM with length 50 aa sounds correct with read length 150nt, because that means that the read completely covers a piece of a protein sequence. You can take the reported sequences in the output file and put them into [blastp](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins) to double check the read's origin.

**Comment by jfourquet2** [comment]
Thanks for your answer !
So I will use blastp for double check.
It seems normal that for a sample of 91 million reads I have 7 million reads which have a max length (4th column of kaiju MEM mode verbose) of 49 or 50 ?

**Comment by pmenzel** [comment]
It is plausible, when the bugs in your sample are very closely related to the sequences in the reference database, then most reads would be perfect matches.

**Comment by jfourquet2** [comment]
Ok, I will check it ! Thanks a lot !

**Comment by jfourquet2** [comment]
Hello,
I have generated these graphs for one sample where we can see the maximal length of aa found by kaiju for each read (x axis) versus the count or the density of reads for each maximal length (y axis).
In this sample like in all our samples there are a lot of reads which have a length of 49 or 50 aa which are in the database as I said you 1 week ago but why there a few number of reads of length 48 aa ?
![sample1_counts](https://user-images.githubusercontent.com/46443858/53750844-2ace3e80-3eab-11e9-9df5-e33f099974e4.jpg)
![sample1_density](https://user-images.githubusercontent.com/46443858/53750856-30c41f80-3eab-11e9-948a-0d458b801492.jpg)

**Comment by pmenzel** [comment]
Simplified example with reads, each yielding 11 amino acids after translation:
```
Genome:           -----MPROTEINPROTEINPROTEIN*----------------
Translated Read1:      MPROTEINPRO    match length = 11
Translated Read2:     FMPROTEINPR     match length = 10
Translated Read3:    AFMPROTEINP      match length = 9
Translated Read4:      MNROTEINPRO    match length = 9
```

You get this long tail of matches of length 48, 47, etc from reads that either only overlap a fraction with a protein-coding region of the genome (reads 2 and 3 in the example) or because there are mismatches between the protein sequences (read 4 in the example).

**Comment by pmenzel** [comment]
When sampling uniformly from a bacterial genome, most reads will completely fall within a protein-coding region. However, only 1 out of 3 such reads will start in the proper reading frame, which means that for 150nt long reads, 1 out of 3 has can have 50 matching amino acids, whereas 2 out of 3 can have 49 matching amino acids.

**Comment by jfourquet2** [comment]
Thanks a lot for your answers ! I understand now the gap between 49aa and 50aa. The other question I have is about the difference between 48aa and 49aa : why is there a lot of reads (50%) in the 49aa case and only 5% of reads in the 48aa case ?

**Comment by pmenzel** [comment]
Because most reads completely cover protein-coding regions, so they mustl either have 49 or 50 a.a., for perfect matches. Therefore the match length is < 49 only in case of mismatches or partial overlap.

**Comment by jfourquet2** [comment]
Thanks a lot for your explanation, and thanks a lot again for all your answers, it helps me a lot !

**Comment by jfourquet2** [comment]
Hello,
I wanted to correct my previous question about the length of matches in reads with kaiju MEM.
In fact there is no issue, it was an issue with my R script which shows in the first bar of the bar plot the sum of reads match length 11 and 12 ! Now I have this type of graph :
![aWithoutHuman_kaiju_MEM_verbose out_Kaiju_MEM_counts_OK](https://user-images.githubusercontent.com/46443858/59925698-f4f09e00-9438-11e9-999b-0741ce4bdbcd.jpg)
