### ISSUE TITLE
"Control connection closed" when downloading Nr database

### ISSUE THREAD

**Issue by shimingtan** [bioinformatics-centre/kaiju#108]
Hey there! 

I am having some problems with my internet connectivity when downloading the NR database. 

(tsm-py3) tanshiming@S620100019205:~/databases/kaijudb$ makeDB.sh -e -t 10
Downloading file taxdump.tar.gz
.listing                                      [ <=>                                                                                 ]   3.10K  --.-KB/s    in 0.009s  
2019-03-15 17:16:31 URL: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz [3178] -> ".listing" [1]
taxdump.tar.gz                             62%[====================================================>                                ]  28.64M   856KB/s    in 2m 43s  
2019-03-15 17:19:15 (180 KB/s) - Control connection closed.
taxdump.tar.gz                            100%[+++++++++++++++++++++++++++++++++++++++++++++++++++++===============================>]  45.47M   473KB/s    in 1m 48s  
2019-03-15 17:21:07 URL: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz [47678861] -> "taxdump.tar.gz" [2]
Extracting file taxdump.tar.gz
Downloading file nr.gz
.listing                                      [ <=>                                                                                 ]   3.49K  --.-KB/s    in 0.03s   
2019-03-15 17:21:12 URL: ftp://ftp.ncbi.nih.gov/blast/db/FASTA/nr.gz [3570] -> ".listing" [1]
nr.gz                                       0%[                                                                                     ]  33.41M  1.74MB/s    in 3m 59s  
2019-03-15 17:25:11 (143 KB/s) - Control connection closed.
nr.gz                                       0%[                                                                                     ] 431.96M  1.42MB/s    in 9m 33s  
2019-03-15 17:34:48 (712 KB/s) - Control connection closed.
nr.gz                                       1%[>                                                                                    ] 658.68M  2.09MB/s    in 6m 30s  
2019-03-15 17:41:23 (596 KB/s) - Control connection closed.
nr.gz                                       1%[+                                                                                    ] 797.09M  1.67MB/s    in 6m 6s   
2019-03-15 17:47:35 (387 KB/s) - Control connection closed.
nr.gz                                       2%[+                                                                                    ] 978.47M  1.18MB/s    in 5m 12s  
2019-03-15 17:52:54 (595 KB/s) - Control connection closed.
nr.gz                                       3%[+>                                                                                   ]   1.51G  23.2KB/s    in 19m 52s 
2019-03-15 18:12:54 (490 KB/s) - Control connection closed.
nr.gz                                       4%[++>                                                                                  ]   1.91G  1.89MB/s    in 13m 46s 
2019-03-15 18:26:49 (503 KB/s) - Control connection closed.
nr.gz                                       4%[+++>                                                                                 ]   2.07G  1.16MB/s    in 6m 56s  
2019-03-15 18:33:55 (417 KB/s) - Control connection closed.
nr.gz                                       5%[++++                                                                                 ]   2.36G  59.0KB/s    in 8m 19s  
2019-03-15 18:42:26 (592 KB/s) - Control connection closed.
nr.gz                                       5%[++++                                                                                 ]   2.39G  1.44MB/s    in 3m 51s  
2019-03-15 18:46:29 (148 KB/s) - Control connection closed.
nr.gz                                       6%[++++>                                                                                ]   2.87G   726KB/s    in 13m 32s 
2019-03-15 19:00:14 (626 KB/s) - Control connection closed.
nr.gz                                       7%[+++++>                                                                               ]   3.27G  1.17MB/s    in 11m 20s 
2019-03-15 19:11:47 (611 KB/s) - Control connection closed.
nr.gz                                       8%[++++++                                                                               ]   3.51G   731KB/s    in 6m 27s  
2019-03-15 19:18:27 (644 KB/s) - Control connection closed.
nr.gz                                       8%[++++++>                                                                              ]   3.72G   637KB/s    in 6m 17s  
2019-03-15 19:24:57 (603 KB/s) - Control connection closed.
nr.gz                                       8%[+++++++                                                                              ]   3.87G   538KB/s    in 4m 7s   
2019-03-15 19:29:17 (603 KB/s) - Control connection closed.
nr.gz                                       9%[+++++++                                                                              ]   4.11G  2.03MB/s    in 6m 29s  
2019-03-15 19:35:59 (647 KB/s) - Control connection closed.
nr.gz                                       9%[+++++++>                                                                             ]   4.16G   617KB/s    in 3m 25s  
2019-03-15 19:39:38 (274 KB/s) - Control connection closed.
nr.gz                                      11%[++++++++>                                                                            ]   5.01G   134KB/s    in 21m 56s 
2019-03-15 20:01:47 (680 KB/s) - Control connection closed.
nr.gz                                      12%[+++++++++>                                                                           ]   5.43G  2.14MB/s    in 13m 3s  
2019-03-15 20:15:02 (556 KB/s) - Control connection closed.
nr.gz                                      12%[++++++++++                                                                           ]   5.63G   405KB/s    in 5m 13s  
2019-03-15 20:20:28 (688 KB/s) - Control connection closed

Is there a way to continue downloading the database (similar to the -c options with wget) if the download is interrupted?

Thanks!

**Comment by pmenzel** [comment]
Hi,
the nr.gz file is downloaded using wget, so now I added the option `-c` to the wget command inside makeDB.sh and kaiju-makedb programs. So you can do `git pull` and `cd src; make` to update them and try again.

Alternatively, you can also download the NR+euk index from the kaiju web server page (link at bottom of blue box).

Peter
