### ISSUE TITLE
Coordinates of the read match

### ISSUE THREAD

**Issue by jfourquet2** [bioinformatics-centre/kaiju#109]
Hello,
I did not see in kaiju settings the possibility of having the coordinates of the match in the read. Is it possible to have it with a setting which I didn't see or with an other technique ?
Thanks a lot in advance !

**Comment by jfourquet2** [comment]
Hello,
I reopen this issue to know if someone have an idea for a setting or an other technique to have coordinates of match in the read?
Thanks a lot in advance!

**Comment by pmenzel** [comment]
Hi,
sorry, but it is currently not possible to print out the match position and it would require some changes in the code for that, which I currently cannot do. I you really need it, you could in principle run kaiju in verbose mode and extract the matching sequences from the output file and then grep them in the kaiju_db_*.faa file.

**Comment by jfourquet2** [comment]
Hi,
Thanks a lot for your answer! I will try to grep matching sequences. Thanks again !
