### ISSUE TITLE
Problem with kaiji-makedb

### ISSUE THREAD

**Issue by msegurawang** [bioinformatics-centre/kaiju#110]
The refseq viral release has changed and ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.3.genomic.gbff.gz doesn't exist any more. Therefore, downloading the refseq/viral/progenomes databases breaks after it doesn't find this url... Can solve just by removing the corresponding lines.

**Comment by pmenzel** [comment]
thanks for reporting the issue!
