### ISSUE TITLE
Error: Could not open file /webdata/tmp/kaiju/database/nodes.dmp 

### ISSUE THREAD

**Issue by pwang16** [bioinformatics-centre/kaiju#111]
Hi, how should I do if I find this error message: "Error: Could not open file /webdata/tmp/kaiju/database/nodes.dmp" after I submit my job?

Thanks,
Peng

**Comment by pmenzel** [comment]
Hi,
we had maintenance on the server the last days, so the kaiju web server was not working temporarily. Now it should be ok again.
Peter
