### ISSUE TITLE
Building of nr_euk database does not finish

### ISSUE THREAD

**Issue by Tamtatatam** [bioinformatics-centre/kaiju#112]
I tried building the nr_euk database, but the "Reading accession to taxon id map from file nr_euk/prot.accession2taxid" step does not finish. I do not get an error message, but the script has already been running for six hours, which I guess is not normal (?). 
There is enough hard disk space available (300Gb), an building the much smaller virus database worked without problems. 
Any idea on how to solve this? Thanks!

**Comment by pmenzel** [comment]
Hi,
I think you are probably running out of RAM. I recommend to have at least 100GB of RAM for building the nr_euk database.

**Comment by Tamtatatam** [comment]
Thanks. That might be the case, yes. Only 16GB available on this computer.So that means there is absolutely no chance to build the nr_euk without having 100GB of RAM available?

**Comment by pmenzel** [comment]
Yes, you would need that much, also for running kaiju after building the index.
btw, you can also use the [web server ](http://kaiju.binf.ku.dk/server).

**Comment by Tamtatatam** [comment]
Thanks, I will give it a try!
Just a quick follow up question: Does the web server use an E-value when run in greedy mode?

**Comment by pmenzel** [comment]
This has been on my to-do list for a while, but at the moment you can only set a threshold for match length and score in Greedy mode, sorry.

**Comment by s4251484** [comment]
@pmenzel hi there, i tried building nr_euk with 100gb memory, but still got my job killed - any recommendation? 120gb (max) also failed actually, but i dont have the screenshot to show.

<img width="510" alt="Screen Shot 2019-04-19 at 6 17 26 am" src="https://user-images.githubusercontent.com/42083931/56388668-ee904b00-626a-11e9-8f77-538b4265aab0.png">

**Comment by pmenzel** [comment]
Seems like you need a bit more RAM.. that database is growing quite fast. Also you can try to set number of threads to 1 and also maybe change the exponentSA_NR variable to 6 in kaiju-makedb, which should reduce the memory requirement a bit.

You can also download a recent kaiju index from here: http://kaiju.binf.ku.dk/server

**Comment by s4251484** [comment]
> Seems like you need a bit more RAM.. that database is growing quite fast. Also you can try to set number of threads to 1 and also maybe change the exponentSA_NR variable to 6 in kaiju-makedb, which should reduce the memory requirement a bit.
> 
> You can also download a recent kaiju index from here: http://kaiju.binf.ku.dk/server

@pmenzel hi happy easter! yea i tried threads 2 and variable 6 but still >.< pbs job was killed. i guess downloding the index from your server is my only choice now. hopefully there will be solution to this issue eventually! the database is going bigger and bigger in one direction :p

**Comment by pmenzel** [comment]
@s4251484 Thanks. Running kaiju with the 2019 index from the web server required approx. 92GB of RAM. The solution to the problem is to install more RAM :)

**Comment by nextgenusfs** [comment]
FYI -- building `nr_euk` database today resulted in max memory usage of 158.422 GB.  Might be helpful to update the docs to reflect the amount of RAM needed (I thought I would only need 100 GB based on the 92GB figure that is in several places) -- but this is likely to increase in the future!

**Comment by pmenzel** [comment]
I updated the [table](https://github.com/bioinformatics-centre/kaiju#creating-the-reference-database-and-index) and added the memory requirements for kaiju-makedb for each of the source databases, built on 2019-06-25.

**Comment by EugeneMwanza** [comment]
Hello, I am working on a project, soil metagenomics, using Kaiju outputs from the nr-euk database to perform taxonomics classification .I would like to know how to better interpret all the columns in the output files before I do R analysis.Thank you.
