### ISSUE TITLE
refseq fmi file

### ISSUE THREAD

**Issue by freedomq8** [bioinformatics-centre/kaiju#113]
Hi there, 

I am new to the field and to your tool as well. I enjoyed the data i generated using the website version and now i am trying to do the same locally. I downlaoded the latest version (kaiju version 1.6.3)
and 
`kaiju-makedb -s refseq`

the download of the files finished but i dont see the fmi file (refseq/kaiju_db_refseq.fmi) needed to run the program. Do i have to generate this file or my downloading for the refseq failed ? if i need to generated it, how ?

Thanks

**Comment by pmenzel** [comment]
Hi,
please try the latest version of kaiju directly from github, rel 1.6.3 does not have the kaiju-makedb program yet. I am going to make a new release soon, which includes it though.
