### ISSUE TITLE
translated sequences

### ISSUE THREAD

**Issue by TessaTi** [bioinformatics-centre/kaiju#114]
Dear Kaiju team, 

Is it possible to directly retrieve the translated sequences of the classified reads and in case of paired-end couples to get the info of which pair read1/2 got the highest score in the classification?

Thank you for your time, 

Kind regards

**Comment by pmenzel** [comment]
Hi,

when you run kaiju with option `-v`, then you get the sequence that was found in the database and used for the classification in the output file.

The info about the origin of the sequence for paired-ends is not kept.
