### ISSUE TITLE
Download database

### ISSUE THREAD

**Issue by jfourquet2** [bioinformatics-centre/kaiju#116]
Hi,
I have one question about database: when we build a database with Kaiju v1.7.0 (kaiju-makedb -s refseq) the tool download database from ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/ and download only bacteria, archaea and viral ?
Thanks a lot in advance !

**Comment by pmenzel** [comment]
Yes, see [here](https://github.com/bioinformatics-centre/kaiju#creating-the-reference-database-and-index) what the different databases contain.

**Comment by jfourquet2** [comment]
Ok thanks a lot !
