### ISSUE TITLE
Warning: Taxon ID is not contained in nodes.dmp.

### ISSUE THREAD

**Issue by Tamtatatam** [bioinformatics-centre/kaiju#120]
Hi

I have several files from the kaiju webserver and I would like to combine them using kaiju2table.

However, I get dozens of warnings ("Warning: Taxon ID XY is not contained in nodes.dmp."). I tried using the latest nodes.dmp and names.dmp, and also downloaded older versions from NCBI as the webserver uses older databases, but that did not help.

Is that a known and expected problem, or am I using the wrong files? If so, which version should I use?

Thanks!

**Comment by pmenzel** [comment]
Hi

try to download and unpack the file http://kaiju.binf.ku.dk/database/kaiju_index.tgz
and use these nodes and names dmp files, which are the one used by the web server.

**Comment by palc** [comment]
I see a similar issue and error message of hundreds of lines
```
Warning: Taxon ID 2171752 is not contained in nodes.dmp.
Warning: Taxon ID 1940818 is not contained in nodes.dmp.
Warning: Taxon ID 2171752 is not contained in nodes.dmp.
```
I downloaded the kaiju_db_nr_euk.fmi etc. file from Kajiju in March and ran the kaiju via command line last month. I tried both taxdump versions from March and July when combining kaiju.out tables but still same issues.

**Comment by pmenzel** [comment]
This happens when taxonomy IDs are replaces by new IDs, but the old ones are still used in the `nr` database, you can see that in the `merged.dmp` file from `taxdump.tar.gz`:
```
$ grep 1940818 merged.dmp                                                                                                                                                                1940818 |       2548426 |

$ grep 2171752 merged.dmp                                                                                                                                                                2171752 |       2080658 |
```
So, 1940818 was replaced with 2548426 and 2171752 with 2080658.
If it is just these two IDs in, then you could simply replace them manually.

**Comment by astromicronaut** [comment]
I also have  files from the kaiju webserver and I would like to combine them using kaiju2table, but trying with all the options I cant really merge, kaiju2table only paste the results in rows in the same file repiting taxons and creating a big file. What I need is create a file that unifique taxons and just add columns for each sample. Could anyone help me? please
