### ISSUE TITLE
Error with Kaiju-makedb -s refseq

### ISSUE THREAD

**Issue by Duannai** [bioinformatics-centre/kaiju#121]
After the download of refseq database, there was no `kaiju_db_*.fmi` file and the software did not show any error, but there were `nodes.dmp` and `names.dmp` files which might not be constructed completely.

But when I used the command `kaiju-makedb -s nr`，it showed `Writing FM index to file ... DONE`, and there are `kaiju_db_*.fmi`,`nodes.dmp` and `names.dmp` files.

So is it ok to use refseq index without `kaiju_db_*.fmi`?

Thanks in advance.

**Comment by pmenzel** [comment]
Hi,

the `nodes.dmp` and `names.dmp` are just extracted from the downloaded `taxdump.tar.gz` file.
If `kaiju-makedb -s refseq` would finish correctly, then you should find the file `refseq/kaiju_db_refseq.fmi`, which is needed to run kaiju.

If it doesn't work out, you can also just download the file from the web server: http://kaiju.binf.ku.dk/database/kaiju_db_refseq_2019-06-25.tgz

Anyways, if you get `kaiju-makedb -s nr` working, then use this one over the RefSeq database for the classification.

**Comment by Duannai** [comment]
Thanks for prompt answer!
