### ISSUE TITLE
kaiju-makedb multiple taxa?

### ISSUE THREAD

**Issue by charlottecc** [bioinformatics-centre/kaiju#122]
Hi, 

Is it possible to create a database containing the completely assembled and annotated reference genomes of Archaea, Bacteria, and viruses from the NCBI RefSeq database, as well as fungal RefSeq sequences? Or would I have to run my samples through two different databases to classify fungal reads too? 

I'm interested in classifying fungal reads to as they are quite prevalent in my samples. 

Thank you in advance!

**Comment by pmenzel** [comment]
Hi,
both options are possible.
1) creating a combined reference database needs a bit tinkering: first run `kaiju-makedb` with the `fungi` and `refseq` options, and then manually combine the `kaiju_db_*.faa` files into one file (using `cat`), and then run `kaiju-mkbwt` and `kaiju-mkfmi` as described [here](https://github.com/bioinformatics-centre/kaiju#custom-database).

2) you can also run your reads through both databases separately and then combine the output file of each using [kaiju-mergeOutputs](https://github.com/bioinformatics-centre/kaiju#merging-outputs).

**Comment by charlottecc** [comment]
Thank you very much for your reply, I will try your suggestions!
