### ISSUE TITLE
No Permission to Download Kaiju Databases Online

### ISSUE THREAD

**Issue by bstamps** [bioinformatics-centre/kaiju#123]
If this is not the best place to post this issue, I apologize. None of the "newer" databases at http://kaiju.binf.ku.dk/server appear to be available for download via port 80 or 21. Is this known or unintentional?

**Comment by pmenzel** [comment]
There are currently some technical problems with the server, I hope it works again soon!

**Comment by pmenzel** [comment]
It works again.
