### ISSUE TITLE
kaiju2table does not report taxonomic level for viruses

### ISSUE THREAD

**Issue by MarieltonCunha** [bioinformatics-centre/kaiju#126]
Hello everyone,

I am using the kaiju2table tool to convert the kaiju output file to a summary table. However, precisely what I'm interested in, choosing the taxonomic level for virus (-r, for example: genus or species) always returns the percent reads rated to taxon_name = Viruses. Is it possible to characterize Viruses at different taxonomic levels ?

Sorry for a beginner's doubt.

Best Regards,

M. P. Cunha

**Comment by pmenzel** [comment]
Hi,
`kaiju2table` lumps all taxa belonging to viruses together into one entry. You can use option `-e` to expand them to individual viruses, but it will not aggregate them on specific levels levels like family etc, because those are often not well defined for many viral species.
best,
Peter
