### ISSUE TITLE
gzip: kaiju_index_nr.tgz: invalid compressed data--format violated

### ISSUE THREAD

**Issue by kaiwang12** [bioinformatics-centre/kaiju#127]
Hi,

I got an error when decompressing the index file. 

The command I used is "tar -zxvf kaiju_index_nr.tgz". 

The error I got:
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
 
Kai

**Comment by pmenzel** [comment]
Hi, check that the file was downloaded properly. The md5sum should be: 78d732644aaac4ac579bdb73ccb54bcd
