### ISSUE TITLE
nr_euk database keeps failing to download

### ISSUE THREAD

**Issue by Mtd0053** [bioinformatics-centre/kaiju#128]
Hey Peter,
Hope all is going well with you! I have tried downloading the nr_euk database from the Kaiju.binf server and it keeps failing after 24 hrs (I get about 20 GB). Have downloaded the nr only database just fine, although there seems to be a speed limit of ~200 mb. Is there a way to download the nr_euk database from GitHub directly (I looked but may have missed a link there)? or is there a way to keep it from quitting after 24 hrs?
Thanks for your assistance!
-Mere

**Comment by pmenzel** [comment]
Hi,
I just tried to start downloading the file and I got a speed of around 2MByte/s, so it would take around 6h to finish. I am not sure why it terminates after 24h, maybe the server or firewall drops the connection after this time.. Maybe you can try the download from some other place? 

Unfortunately, it's not possible to host files this large on Github.

Peter

**Comment by Mtd0053** [comment]
Thanks so much for your reply... must be New Zealand 🤷🏼‍♀️We will just try to persist through it!
Cheers,
Mere
________________________________
