### ISSUE TITLE
 how to build nodes.dmp and names.dmp from my own protein database

### ISSUE THREAD

**Issue by rocpengliu** [bioinformatics-centre/kaiju#133]
Hi, Kaiju

I am trying to use kaiju on my own protein database. My protein database is much smaller than the database in your website, that could increase the speed a lot.

One of my purpose is to use kaiju to get both taxa classification and functions and i am wondering
1. can i build nodes.dmp and names.dmp from my own protein database?
2. do you have any suggestions of software i can use to build nodes.dmp and names.dmp?

Thank you so much!

**Comment by pmenzel** [comment]
afaik, there is now software for creating these files.
But they are text files and the structure is quite easy, if you want to modify them.
Kaiju only used the "scientific name" rows from names.dmp.
