### ISSUE TITLE
maximum sequences in custom DB?

### ISSUE THREAD

**Issue by dparks1134** [bioinformatics-centre/kaiju#136]
Hi. 

Thank you for your efforts with Kaiju. I am currently using it with a custom DB which works fine for a relatively modest number of genomes (say, <1000). However, with large numbers of genomes (>10,000) I encounter a segfault when doing the profiling. Note that the database still builds without issue. I'm wondering if there is an upper limit on how many sequences can be in the database. Perhaps the sequence identifiers are being stored in a 16-bit int when profiling and thus I am hitting an issue in this regard?

Cheers,
Donovan

**Comment by pmenzel** [comment]
Hi,
custom databases are not treated different than the downloaded databases, the NR databases have more than 100m protein sequences. Make sure to only have the 20 amino acid characters (ACDEFGHIKLMNPQRSTVWY) in your sequences and that the identifiers have no special characters besides ASCII. Does the same fastq input file work with a standard database?

**Comment by dparks1134** [comment]
Thanks for the quick response. I'll poke around to see if there is a bad character in the mix.
