### ISSUE TITLE
Query coverage cut-off 

### ISSUE THREAD

**Issue by miasungeunlee** [bioinformatics-centre/kaiju#137]
Dear Peter,

Thanks for your cool tool, it is very fast and easy to use :) 
I have few questions about the parameters in Kaiju. 
First, what cut-off of query coverage percentage used in Kaiju?
And, in the output file, the matching fragment sequences (amino acid seq) are the sequences from nr database or is it my query sequence? 

To get most accurate annotation, what parameters would you recommend ? 
I used as recommended, nr database and greedy mode allowing only 5 mismatches and e-value 10-3. 
And according the Kaiju result by comparing with other tools (blastx, diamond using other database), i was confusing. When i blasted the contig (nucleotide) using blastx or diamond blastx with nr database on NCBI, but the hit doesn't give same result (not all the time, but somes), how it can be explained..? 

Best wishes
Mia

**Comment by pmenzel** [comment]
Hi,

> Thanks for your cool tool, it is very fast and easy to use :)
> I have few questions about the parameters in Kaiju.
> First, what cut-off of query coverage percentage used in Kaiju?

There is not coverage cutoff used, just the score of the matching sequence and the e-value (if set). But you could calculate the coverage easily by yourself using the length of the matching sequence from the output file.

> And, in the output file, the matching fragment sequences (amino acid seq) are the sequences from nr database or is it my query sequence?

from the database.

> To get most accurate annotation, what parameters would you recommend ?
> I used as recommended, nr database and greedy mode allowing only 5 mismatches and e-value 10-3.

sounds good. This will probably give you low abundance false positive hits, which you could filter out downstream.

> And according the Kaiju result by comparing with other tools (blastx, diamond using other database), i was confusing. When i blasted the contig (nucleotide) using blastx or diamond blastx with nr database on NCBI, but the hit doesn't give same result (not all the time, but somes), how it can be explained..?

kaiju trades sensitivity versus speed by looking for (mostly) exact matches between rreads and database, whereas blastx and diamond can also identify less perfect matches.

**Comment by miasungeunlee** [comment]
Thank you for your clear answers !! :)
Best wishes
Mia
