### ISSUE TITLE
'Unclassified' and 'cannot be assigned' 

### ISSUE THREAD

**Issue by rachaellappan** [bioinformatics-centre/kaiju#138]
Hi Peter,

I am summarising my kaiju output with kaiju2table at phylum level, requesting `-l superkingdom,phylum`.

Could you please clarify the distinction between the taxonomy assignment 'unclassified' and 'cannot be assigned to a (non-viral) phylum'?

I understand the former refers to reads that match nothing at all. Does the latter mean that the match is just too ambiguous to be assigned to a phylum (but it's definitely not viral, but also too ambiguous to even be assigned a kingdom)?

Cheers,
Rachael

**Comment by pmenzel** [comment]
Hi,

correct, reads that are assigned to a taxonomy level above phylum are counted towards the category `cannot be assigned to a (non-viral) phylum`. For example, the NCBI taxonomy summarizes some phyla into groups, e.g. [Terrabacteria goup](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=1783272&lvl=3&lin=f&keep=1&srchmode=1&unlock) or [FCB group](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=1783270&lvl=3&lin=f&keep=1&srchmode=1&unlock).

It can also happen that a read is assigned above kingdom level, e.g. if the matching sequence is shared between bacteria and Archaea, it will be assigned to [cellular organisms](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=131567&lvl=3&lin=f&keep=1&srchmode=1&unlock).
You can look at the kaiju output file and look for the taxon id 131567 in the third column to find those reads.

If a sequence is shared between a virus and a cellular organism, it will be assigned to the root node with taxon id = 1.

**Comment by rachaellappan** [comment]
Thanks Peter.

So once in the "cannot be assigned to phylum" category, the kingdom information is lost? I can't account for the number of reads in that category with reads classified only to "root" (1) or to "cellular organisms" (131567) so it seems that most of these reads at least have a kingdom classification.

**Comment by pmenzel** [comment]
You could also try to make a krona chart, there you will see the number of reads that go into each kingdom, but not into a phylum.
