### ISSUE TITLE
'make' error

### ISSUE THREAD

**Issue by HeringKim** [bioinformatics-centre/kaiju#139]
Hi
I've git cloned kaiju and I'm trying to 'make' in my ubuntu system.
I got the error message as following: 
Afterwards, I can't find bin directory. Isn't it work?
PLS, help me.
-------------------------------------------------------------------------------------------------------
$ make
make -C bwt/ 
make[1]: Entering directory &apos;/home/avidia/kaiju/src/bwt&apos;
gcc -O3 -g -Wno-unused-result   -c -o mkbwt.o mkbwt.c
gcc -O3 -g -Wno-unused-result   -c -o readFasta.o readFasta.c
gcc -O3 -g -Wno-unused-result   -c -o suffixArray.o suffixArray.c
gcc -O3 -g -Wno-unused-result   -c -o multikeyqsort.o multikeyqsort.c
gcc -O3 -g -Wno-unused-result   -c -o sequence.o sequence.c
gcc   mkbwt.o readFasta.o suffixArray.o multikeyqsort.o sequence.o  -lpthread -lm -o mkbwt
gcc -O3 -g -Wno-unused-result   -c -o mkfmi.o mkfmi.c
gcc -O3 -g -Wno-unused-result   -c -o bwt.o bwt.c
gcc -O3 -g -Wno-unused-result   -c -o compactfmi.o compactfmi.c
gcc   mkfmi.o bwt.o suffixArray.o compactfmi.o  -lpthread -lm -o mkfmi
make[1]: Leaving directory &apos;/home/avidia/kaiju/src/bwt&apos;
g++ -O3 -pthread -std=c++11 -DNDEBUG -I./include -I./include/ncbi-blast+ -c -o kaiju.o kaiju.cpp
In file included from <b>kaiju.cpp:39</b>:
<b>./include/zstr/zstr.hpp:15:10:</b> <font color="#CC0000"><b>fatal error: </b></font>zlib.h: No such file or directory
   15 | #include <font color="#CC0000"><b>&lt;zlib.h&gt;</b></font>
      |          <font color="#CC0000"><b>^~~~~~~~</b></font>
compilation terminated.
make: *** [makefile:75: kaiju.o] Error 1
-------------------------------------------------------------------------------------------------------------------------------

**Comment by pmenzel** [comment]
Seems like zlib is missing on your system. You can also just download the static compiled files from kaiju github release page and use those.
