### ISSUE TITLE
Progenomes

### ISSUE THREAD

**Issue by carolinasuarez** [bioinformatics-centre/kaiju#141]
_kaiju-makedb_ doesn't work for proGenomes. The file at http://progenomes.embl.de/data/repGenomes/representatives.proteins.fasta.gz doesn't exist.

I think the latest version of progenomes is at http://progenomes.embl.de/data/repGenomes/freeze12.proteins.representatives.fasta.gz

**Comment by pmenzel** [comment]
Thanks for reporting!
