### ISSUE TITLE
Difference between Unclassified read and Classified read with "no rank" affiliated ?

### ISSUE THREAD

**Issue by greboul** [bioinformatics-centre/kaiju#142]
Dear Kaiju developers,

I have encountered result like this while using Kaihu 1.7.1 and adding names to the result file:
`C       SRR490128.85558 1       84      1126885,1930849,        WP_085113560.1,YP_006546303.1,  CINTIKEIQTYKYREDKDGNV,  `

Clearly, no taxonomy was added for this classified read because his Taxon ID was set to 1 meaning no rank.

I then looked into the names.dmp and the EBI website and both agreed on the following taxonomy for the 2 hits of this read:
WP and 1930849: Thermoanaerobacterium sp. PSU-2
YP and 1126885: Thermoanaerobacterium phage THSA-485A

Thus, I guess that the LCA algorithm of Kaiju could not resolve neither choose between 'cellular organism' and 'Viruses' as root toxonomical level, so it outputs nothing.

But I was wondering if you could explain or clarify the biological difference in a Classified read with "no rank" affiliated and an Unclassified read? Because i could not find my answer neither in the paper or in the manual.

Thanks a lot,
Guillaume

**Comment by pmenzel** [comment]
Hi Guillaume,

the taxon id = 1 denotes the root node of the NCBI taxonomic tree, which has Viruses (taxon id  = 10239) and cellular organisms (taxon id = 131567) as direct child nodes. Bacteria (2) etc. are in turn child nodes of cellular organisms. 
So this means, that a sequence matching a phage and a bacteria with the same score, will be assigned to the root node by the LCA algorithm. 

Unclassified reads are reads that have no match to any database sequence.
