### ISSUE TITLE
Difference between the 'unclassified' to ''can not be assigned to a (non-viral) phylum' fields.

### ISSUE THREAD

**Issue by leandronascimentolemos** [bioinformatics-centre/kaiju#144]
Dear all,

I have difficulty interpreting the output to generate by  kaiju2table. For example, I don't have any idea the difference between the 'unclassified' to ''can not be assigned to a (non-viral) phylum' fields. I identified 28.7% of 'cannot (...) phylum' and '31% of unclassified'. How to interpret it?

Thank you very much.

**Comment by noirot** [comment]
Apparently, the reads are assign but not at phylum level, probably at kingdom or superkingdom level.
If you set -r species, the number is much more higher.

**Comment by pmenzel** [comment]
Yes correct, the "cannot be assigned to phylum|...|species" line denotes the number of reads that are classifed above this rank. Note that the NCBI taxonomy also groups phyla into groups, e.g. the  [Terrabacteria group](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=1783272&lvl=3&keep=1&srchmode=1&unlock) .

**Comment by pmenzel** [comment]
Hi,

> in a number of my samples, the "cannot be assigned to a (non-viral) species" field accounts for 70-80% of my reads, which seems like quite a lot. However, since I set my "-r" parameter to "species", does this indicate that those 70-80% of reads are accounted for in higher taxonomic levels (order, class, phylum, etc.)?

Yes, those 70%-80% reads have multiple best matches, which are to different species, and are therefore assigned to higher ranks using the LCA.

> Are these counts in any way already presented in the table (for example, a field that shows phylum, class, order, family but loses the genus and species)? Or are these reads completely separate from those annotations and all information is lost?

Reads assigned to higher ranks are all summarized in the row `cannot be assigned to a (non-viral) species`
 
> Is there still a way to obtain the full taxonomic path while also reducing the number of "cannot be assigned to X"? Will setting "-r" at a higher taxonomic rank help with this while still allowing species annotation?

No.

> Or can this be solved by just allowing Kaiju to output the entire taxonomic path (without specifying "-l" which can exclude superphyla, etc.)?

No, you need to specify a rank in kaiju2table. Option `-l` only specifies how the taxon path is displayed.

> I noticed in another comment that you suggested using Kaiju2Krona to visualize how many annotations are present for each taxonomic level to help with this interpretation.

Yes, this is the workaround for getting counts for all ranks.

> However, I have multiple hundred samples and hope to find a more high-throughput way of looking into this if that is possible.

In principle you could run kaiju2table once for each rank of interest with all samples.

You could also run kaiju2krona for every sample and post-process the results.

> I apologize if these are redundant questions, I am just hoping to reduce the "cannot be assigned" percentage as much as I can when interpreting these assignments. Thank you very much for your insight!

You already got most answers right, and it's great to get feedback on how people use the result processing tools. Obviously there is also room for improvement on how to process results from multiple samples by these programs.

Maybe you need to think about which kind of analysis you want to do and which format the data needs to be in for that.
Then look which steps are necessary to format the data appropriately. Let me know if you have further questions.
