### ISSUE TITLE
Using assembled contigs - accessing intermediate score files?

### ISSUE THREAD

**Issue by acciardo** [bioinformatics-centre/kaiju#145]
Hello,

I have been running Kaiju using assembled contigs and I just recently realized that Kaiju only reports the best match from the entire contig, even if it contains many protein coding sequences. 

My question is - is it possible to access some sort of intermediate file that would list all of the scores/results of each match within a specific contig? Ideally, I would like to see every match and score (given the E-value and other thresholds I would set before running) for a given contig rather than only the best match.

Thanks!

**Comment by pmenzel** [comment]
Hi,

Kaiju will only report the best match, all intermediate matches are discarded during the search.
For getting the most information about suboptimal matches, I would use blast for long contigs.

best
Peter
