### ISSUE TITLE
Is it possible to use GTDB as a reference database for kaiju?

### ISSUE THREAD

**Issue by ilnamkang** [bioinformatics-centre/kaiju#146]
Hi,

I'm just curious.

Is it possible to use GTDB as a reference database for Kaiju?  If It's not possible currently, are there any future plans?

ICYMI, GTDB is available at https://gtdb.ecogenomic.org/.

I think it would be nice if GTDB can be used as a reference database for Kaiju, because it seems to me that GTDB is one of very few databases that provides genome sequences together with well-curated taxonomy.

Thanks.

**Comment by pmenzel** [comment]
I am not that familiar with the GTDB taxonomy, but kaiju uses the NCBI taxon ID system throughout. So it would only be possible to use GTDB if each contained protein sequence could be mapped to an NCBI taxon ID, like with the progenomes database..
