### ISSUE TITLE
Segmentation fault with newest nr+euk database downloaded from the web

### ISSUE THREAD

**Issue by DaGaMs** [bioinformatics-centre/kaiju#148]
I tried running kaiju with the latest progenomes database that I downloaded from the web, and that works fine:

```
$  kaiju -v -z 8 -t progenomes_2019-06-25/nodes.dmp -f progenomes_2019-06-25/progenomes/kaiju_db_progenomes.fmi -i test_1.fastq.gz -j test_2.fastq.gz -o test.kaiju.txt
20:41:34 Reading database
 Reading taxonomic tree from file progenomes_2019-06-25/nodes.dmp
 Reading index from file progenomes_2019-06-25/progenomes/kaiju_db_progenomes.fmi
Output file: test.kaiju.txt
20:41:50 Start classification using 8 threads.
20:41:53 Finished.
```

However, when I try the same with the nr+euk database, I get:

```
$ kaiju -v -z 8 -t nr+euk_2019-06-25/nodes.dmp -f nr+euk_2019-06-25/nr_euk/kaiju_db_nr_euk.fmi -i test_1.fastq.gz -j test_2.fastq.gz -o test.kaiju.txt
20:47:17 Reading database
 Reading taxonomic tree from file nr+euk_2019-06-25/nodes.dmp
 Reading index from file nr+euk_2019-06-25/nr_euk/kaiju_db_nr_euk.fmi
Segmentation fault
```

The `.tgz` file downloaded fine and I didn't see any error message when unpacking the archive. The sha1sum of the `kaiju_db_nr_euk.fmi` file is `e5db99dc5c4f7bbf1d958d76967fbd359f7f781a` - does that match yours? Other than a download error, what could be the problem here?

**Comment by DaGaMs** [comment]
Ok, it seems it was a memory issue - increasing the hard memory limit of my cluster jobs to > 100G (from 90G before) made it run ok. Very unusual, normally the grid scheduler kills a job, rather than the program "sensing" that the memory is insufficient. Anyway, apologies for the confusion.

**Comment by pmenzel** [comment]
Usually segmentation faults are due to insufficent free memory. I updated the [table](https://github.com/bioinformatics-centre/kaiju#creating-the-reference-database-and-index) with the memory requirements for the current database from May 2020: For nr+euk one now needs 117GB for running kaiju and 194GB for creating the kaiju index with `kaiju-makedb`.
