### ISSUE TITLE
Taxonomy assignment of predicted proteins

### ISSUE THREAD

**Issue by davidmartinad200** [bioinformatics-centre/kaiju#15]
Hi,
I´m running an illumina metagenomics WGS experiment (2x150bp). 
I have assembled my metagenomes with Megahit and predicted genes using prodigal and converted those to proteins. 
Now I would like to assign the taxonomy of the proteins and was wondering if kaiju is suitable for that ? (using refSeq as a database). 

( A second option would be to run hmm on a marker genes databases but i found this too restrictive at the moment since you may miss some species)., althought there are at least 4 to 5 databases of marker genes out there that could be used.

Thanks for your advice.
david

**Comment by pmenzel** [comment]
Hi David,
yes, you can use Kaiju for assigning your predicted protein sequences to the taxonomy. 
You can just use the fasta file with the predicted protein sequences as input and set option `-p` when you have amino acid sequences as input for Kaiju.
best, Peter
