### ISSUE TITLE
Running kaiju...

### ISSUE THREAD

**Issue by dinakaran-svgev** [bioinformatics-centre/kaiju#151]
Hi all
      I am a post-doctoral fellow from India. When I am running kaiju through command line interface, the process gets **killed** at the Running kaiju step. Until this step, everything is all right. But, I am not getting output exactly at this step and the process gets killed at this step. Why is this happening? Is this because of less RAM capacity? We are using a system with 4GB RAM processor and 1TB hard disk storage. Kindly reply. Please somebody help.

**Comment by pmenzel** [comment]
Yes, 4GB is too small for most reference databasaes. Have a look at the [table](https://github.com/bioinformatics-centre/kaiju#creating-the-reference-database-and-index) in the README file regarding the required amount of RAM for each database.
