### ISSUE TITLE
kaiju-makedb command not found

### ISSUE THREAD

**Issue by NikkiCase** [bioinformatics-centre/kaiju#152]
Hi! 

I have downloaded kaiju as suggested on README.md and am trying to use the kaiju-makedb command in the kaiju/bin/kaijudb directory but when I try to run kaiju-makedb it says the command is not found. 

Similarly when I try to run any command starting with kaiju like kaiju man - the command is not found. I am wondering if I made a mistake in the download process but I am not sure where...

Thank you for your help!

**Comment by pmenzel** [comment]
Hi,
in the Linux shell, you need to use the full path or the relative path to the executable that you want to run.

For example:
```
git clone https://github.com/bioinformatics-centre/kaiju.git
cd kaiju/src
make
cd ../..
mkdir kaijudb
cd kaijudb
../kaiju/bin/kaiju-makedb -s <DB>
```
