### ISSUE TITLE
How to get taxon path counts? 

### ISSUE THREAD

**Issue by ctlshcxy** [bioinformatics-centre/kaiju#153]
Sorry, I failed to obtain taxon path counts by using kaij2table command. all I got were just total amounts of percent, reads, taxon_id, and taxon_name. how to get taxon path counts data like what we can obtain on web server?

**Comment by fbucchini** [comment]
Hi, 

I think the output file you're looking for is produced by the `kaiju2krona` command, taking unclassified sequences into account (`-u` flag). 

For example: `kaiju2krona -u -i kaiju.out -o kaiju_taxon_path.out -t nodes.dmp -n names.dmp`.

**Comment by ctlshcxy** [comment]
> Hi,
> 
> I think the output file you're looking for is produced by the `kaiju2krona` command, taking unclassified sequences into account (`-u` flag).
> 
> For example: `kaiju2krona -u -i kaiju.out -o kaiju_taxon_path.out -t nodes.dmp -n names.dmp`.

Great! you're right!
