### ISSUE TITLE
Can you share only names.dmp and nodes.dmp of kaiju web server?

### ISSUE THREAD

**Issue by astromicronaut** [bioinformatics-centre/kaiju#158]
Thank for the kaiju web server. But In cant download the names.dmp and nodes.dmp because is integrated in the file tgz, the size of that file is huge, and the speed is very low for the download,  I've been trying for days.
Can you share us only the files names.dmp and nodes.dmp of NCBI BLAST nr +euk of  2017-05-16 , for work with kaiju2table please?
To clarify, If I try with kaiju-makedb , but the version is diferent and i have problems with kaiju2table.
If exist other method to obtain this files of kaiju server version, please comment us.

**Comment by pmenzel** [comment]
Hi,
try this [link](https://www.dropbox.com/s/gr4g1qz5vnt56ce/namesnodes.zip?dl=0)

**Comment by astromicronaut** [comment]
Thank you very much!
I already verified.
These files work fine with kaiju2table and kaiju web server output using NCBI BLAST nr +euk of 2017-05-16.
