### ISSUE TITLE
relation taxdump files and fmi indexes

### ISSUE THREAD

**Issue by EricDeveaud** [bioinformatics-centre/kaiju#159]
Hello, 

should I use the exact same nodes.dmp and names.dmp used to build fmi indexes.

my question is du to that while building some kaiju databases I noticed that nodes.dmp and names.dmp changed beetween yesterday (2020-10-29) and today (2020-10-30)

**Comment by pmenzel** [comment]
Yes when running kaiju, you should use the dmp files from the directory where you made the kaiju database.
(one day difference is probably not a big problem though)

**Comment by EricDeveaud** [comment]
so maybee it will worth the information on kaiju databases download page to have  a note about this 

as today, all archives expands with the follwing structure
```
nodes.dmp
names.dmp
kaiju_db_DBNAME.fmi
```
so names.dmp and nodes.dmp may be overwritten with different versions regarding the DB you download and extract
 
we choose to provide on our cluster the DB with the following structure 

```
nr -> nr-2020-11-02/
nr-2020-11-02/ kaiju_db_nr.fmi 
                          names.dmp
                          nodes.dmp
plasmids -> plasmids-2020-10-29/
 plasmids-2020-10-29/ kaiju_db_plasmids.fmi
                                        names.dmp
                                        names.dmp
```
and so on.. 

and taught our users to use databases// tax nodes//names from the same directoy. to avoid problems

regards

Eric
