### ISSUE TITLE
refseq sections :: awk generate incorrect urls when no url in $20

### ISSUE THREAD

**Issue by EricDeveaud** [bioinformatics-centre/kaiju#160]
Hello, 

on our cluster as compute nodes does not have access to internet we had to generate kaiju databases in 2 steps oout of the kaiju-makedb script
1) download datas
2) create index

while dwonloading datas we noticed that for bacteria section of refseq, we had some invalid urls generated by the wak expression used in kaiju-makedb scritpt

see
```
bigmess:~/tmp > DB=`pwd`
bigmess:~/tmp > wget -nv -O $DB/assembly_summary.archaea.txt ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/assembly_summary.txt
2020-11-03 18:48:22 URL: ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/assembly_summary.txt [359824] -> "/home/edeveaud/tmp/assembly_summary.archaea.txt" [1]
bigmess:~/tmp > wget -nv -O $DB/assembly_summary.bacteria.txt ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/assembly_summary.txt
awk 'BEGIN{FS="\t";OFS="/"}$12=="Complete Genome" && $11=="latest"{l=split($20,a,"/");print $20,a[l]"_genomic.gbff.gz"}' $DB/assembly_summary.bacteria.txt $DB/assembly_summary.archaea.txt > $DB/downloadlist.txt
bigmess:~/tmp > grep -v ^ftp downloadlist.txt 
na/na_genomic.gbff.gz
na/na_genomic.gbff.gz
na/na_genomic.gbff.gz
na/na_genomic.gbff.gz
```

we tracked the problem to some entries from bacteria/assembly_summary.txt, du to field 20 not holding an url

after changing the awk expression to check that field 20 starts with  `ftp:` problem solved.

here's  the fixed aw expression 
`awk 'BEGIN{FS="\t";OFS="/"}$12=="Complete Genome" && $11=="latest" && $20 ~ /^ftp:/ {l=split($20,a,"/");print $20,a[l]"_genomic.gbff.gz"}' `

regards

Eric

**Comment by pmenzel** [comment]
Thanks Eric!
I will integrate your fix.
btw, you can also use the option --no-download for kaiju-makedb to make the database from pre-downloaded files.
