### ISSUE TITLE
codon table used

### ISSUE THREAD

**Issue by rocpengliu** [bioinformatics-centre/kaiju#162]
Hi, Peter

I am wondering which codon table are you used in KAIJU for translation?
I have searched online and find there are so many potential codon tables (https://en.wikipedia.org/wiki/List_of_genetic_codes)

Thank you.

**Comment by pmenzel** [comment]
Hi

it uses table 1 from your link, see [here](https://github.com/bioinformatics-centre/kaiju/blob/42e73d0f4f262cee5e6f34b2b18349ce731b953b/src/ConsumerThread.cpp#L118) for the code.
