### ISSUE TITLE
Refseq for eukaryotic reads?

### ISSUE THREAD

**Issue by catarinaloureiro** [bioinformatics-centre/kaiju#164]
Hi!

I ran kaiju on a metagenomic dataset that I know contains eukaryotes, with the db available for download a the webserver - refseq 2020-05-25 (17GB).

However there arent any reads annotated to the eukaryotic domain. Any ideas why this is?

Thanks!

**Comment by pmenzel** [comment]
Hi,
the kaiju refseq database only contains bacteria, Archaea and viruses. The only kaiju database containing eukaryotes is the `nr_euk` database.

**Comment by catarinaloureiro** [comment]
Hi! 

Thanks for the reply!
I've tried now with the nr_euk db but a couple strange things occurred:

no stdout is produced, while with the refseq I got:
14:04:31 Reading database
 Reading taxonomic tree from file /databases/kaiju/kaiju_refseq/nodes.dmp
 Reading index from file /databases/kaiju/kaiju_refseq/kaiju_db_refseq.fmi
Output file:kaiju_refseq_gb126.out
14:04:56 Start classification using 24 threads.
14:53:00 Finished.
Is this an indication of issues with the run?

when making the summary file (specifying the same database location as for the assignment run):
Warning: Taxon ID 2080518 is not contained in /work/kaiju_nr_euk_db/nodes.dmp.
Warning: Taxon ID 2080517 is not contained in /work/kaiju_nr_euk_db/nodes.dmp.

**Comment by catarinaloureiro** [comment]
(update) - when I run:
kaiju -z 24 -t /work/kaiju_nr_euk_db/nodes.dmp -f /work/kaiju_nr_euk_db/kaiju_db_nr_euk.fmi -i /work/Gb1_DNA_1_Q20_m50_phix.fq.gz -j /work/Gb1_DNA_2_Q20_m50_phix.fq.gz -o /work/kaiju_annotation/kaiju_nr_euk_v_gb1.out -v

I also get a lot of warnings 
Warning: Taxon ID 2080517 in database is not contained in taxonomic tree.
Warning: Taxon ID 2080518 in database is not contained in taxonomic tree.
Warning: Taxon ID 114399 in database is not contained in taxonomic tree.
Warning: Taxon ID 2080516 in database is not contained in taxonomic tree.
(...)

**Comment by catarinaloureiro** [comment]
@pmenzel any comments here? still struggling with this unfortunately.

**Comment by pmenzel** [comment]
Did you use the same nodes.dmp and names.dmp file from the extracted tar.gz file? If it's just a few warnings, you can just ignore them..

**Comment by LeeBergstrand** [comment]
@catarinaloureiro You should not the nr_euk database has eukaryotic references for only fungi and microbial eukaryotes (e.g., protists.)

As per the read me.

| Option | Description | Sequences<sup>\*</sup> | RAM in GB (makedb)<sup>\*</sup> |
| --- | --- | --- | --- |
| `nr_euk` | Like option `-s nr` and additionally include proteins from fungi and microbial eukaryotes, see taxon list in `bin/kaiju-taxonlistEuk.tsv`. | 240M | 133 (222) |

**Comment by LeeBergstrand** [comment]
@pmenzel If I wanted to create a database containing plant proteins and animal proteins, how would I go about this? Would I pull a bunch of eukaryotic proteins from Refseq? Then use the full `nodes.dmp` file from NCBI?

**Comment by pmenzel** [comment]
sure, if you can live with the proteins found in the blast `nr` database, you can also just modify the `bin/kaiju-taxonlistEuk.tsv` file and add your desired taxa there and also remove the bacteria etc. if needed.

**Comment by LeeBergstrand** [comment]
I changed `taxonlistEuk.tsv` to contain the just following:

```
2       Bacteria
2157    Archaea
10239   Viruses
2759    Eukaryota
```

However, I ended up getting the same results as before when `taxonlistEuk.tsv` was unchanged. I used the prebuilt `nr_euk` database for this test.

@pmenzel Does `kaiju_db_nr_euk.fmi` contain data for multicellular eukaryotes? Or does one have to download the entire BLAST NR database from NCBI and build custom BWT and FMI files? Do I need new `nodes.dmp` and `names.dmp` files as well?

**Comment by fbucchini** [comment]
Hi,

Not the developer, but I use Kaiju with the all eukaryotic sequences from NCBi nr. I modified the `taxonList.tsv` like you did. 

This file is used when building the Kaiju index (the final output of which is the `fmi` file you mentioned). So, yes, you’d need to rebuild custom files if you modify the radon list. Be aware that doing so will require of memory! 

Also it would be ideal to have NCBI taxonomy files from the same date to not have any conflicts/warnings.

**Comment by pmenzel** [comment]
Yes, the file `taxonlistEuk.tsv` is used to filter the entries in the downloaded `nr.gz` file before building the index.
So you would need to modify `taxonlistEuk.tsv` in the `kaiju/bin` folder and then run `kaiju-makedb`.

**Comment by LeeBergstrand** [comment]
> I changed `taxonlistEuk.tsv` to contain the just following:
> 
> ```
> 2       Bacteria
> 2157    Archaea
> 10239   Viruses
> 2759    Eukaryota
> ```
> 
> However, I ended up getting the same results as before when `taxonlistEuk.tsv` was unchanged. I used the prebuilt `nr_euk` database for this test. Specifically, I was interested in seeing if I could detect some plant DNA in my samples.
> 
> Does `kaiju_db_nr_euk.fmi` contain data for multicellular eukaryotes? Or does one have to download the entire BLAST NR database from NCBI and build custom BWT and FMI files? Do I need new `nodes.dmp` and `names.dmp` files as well?

Okay. I changed the `taxonlistEuk.tsv` to be as above and than ran `kaiju-makedb`. Kaiju is now picking up multicellular Eukaryotes.

**Comment by arthurvinx** [comment]
> Hi, Not the developer, but I use Kaiju with all eukaryotic sequences from NCBi nr. I modified the `taxonList.tsv` as you did. This file is used when building the Kaiju index (the final output of which is the `fmi` file you mentioned). So, yes, you’d need to rebuild custom files if you modify the taxon list. Be aware that doing so will require of memory! Also it would be ideal to have NCBI taxonomy files from the same date to not have any conflicts/warnings.

@fbucchini, do you build the index using kaiju-makedb, or kaiju-mkbwt followed by kaiju-mkfmi?

I'm trying to figure out how to build the index for the whole nr. The headers from the nr file are not like the expected for kaiju-mkbwt.

The kaiju-makedb command expects the nr to be compressed as a .gz, and to be located inside the nr folder. I manually downloaded the nr and extracted its contents using pigz, but maybe I have to compress it again to use kaiju-makedb.

**Comment by fbucchini** [comment]
I think I used both in the past (last time I updated Kaiju's index is September 2019). 

If you want to use `kaiju-mkbwt` you'd need to feed it the fasta file with correct headers, which is created by `kaiju-makedb` prior to indexing itself. In your case, it should be `kaiju_db_nr_euk.faa`. If you want to do this conversion manually I guess you can check the [kaiju-makedb code](https://github.com/bioinformatics-centre/kaiju/blob/master/util/kaiju-makedb#L243)
