### ISSUE TITLE
Question about custom database

### ISSUE THREAD

**Issue by Ahmed-Shibl** [bioinformatics-centre/kaiju#167]
Hi kaiju developers! first I want to say thanks for this useful and versatile tool!

I had a question - rather than an issue - about building a custom database. Briefly, I have a complex metagenome made of multicellular eukaryotes, unicellular eukaryotes and prokaryotic reads. I wanted to combine the existing `nr_euk` + `viruses` + `fungi` + `mar_db` databases to 16 coral genomes and run kaiju against this custom database - two questions:
1- does `nr_euk` suffice to pick up similar taxonomy when using `viruses` + `fungi` + `mar_db` and so this approach would be redundant?
2- if so, what's the best way to add my custom genomes to `nr_euk`?

Thanks!

**Comment by pmenzel** [comment]
Hi, you can see the taxa used in the nr_euk database [here](https://github.com/bioinformatics-centre/kaiju/blob/master/util/kaiju-taxonlistEuk.tsv). As you can see, it contains already viruses und fungi. I don't know how much extra stuff the mar database contains compared with the NCBI nr database. Before trying to combine databases, I suggest that you run your fastq files throuh the nr_euk and mar databases separately and then maybe just merge the output of both using the kaiju-mergeOutputs tool.

**Comment by Ahmed-Shibl** [comment]
Thanks @pmenzel! I ran my samples on `nr_euk` and yes, I see now that it has everything I'm expecting to find in my metagenomes (including Alveolata) - but of course it's not picking up any coral reads (Anthozoa) and so the Krona output is still not entirely representative. 
Any ideas on how to incorporate them? would I make an independent custom database using all available Anthozoa genomes and merge the output of both using the kaiju-mergeOutputs tool as you suggested..? or do you reckon there's a better (more accurate) way?

**Comment by pmenzel** [comment]
In principle you could add the taxon for 6101 for Anthozoa to this file and run make again, then run kaiju-makedb again. But again it depends how many of those genomes' proteins are actually contained in the BLAST nr database. So it might be worth to make a custom database if you have the genomes available anyways. NB: Remember that kaiju only uses protein sequences, so the lower the protein coding content of a genome is, the more it's abundance is underestimated.

**Comment by Ahmed-Shibl** [comment]
> In principle you could add the taxon id 6101 for Anthozoa to this file and run make again, then run kaiju-makedb again. But again it depends how many of those genomes' proteins are actually contained in the BLAST nr database. So it might be worth to make a custom database if you have the genomes available anyways. NB: Remember that kaiju only uses protein sequences, so the lower the protein coding content of a genome is, the more its abundance is underestimated.

This approach worked nicely. Thanks a lot for this!
