### ISSUE TITLE
Not enough memory allocated for sequence, ERROR: File proteins.bwt containing BWT could not be opened for reading

### ISSUE THREAD

**Issue by marialgk** [bioinformatics-centre/kaiju#170]
Hello! I am master’s student, so I am relatively new to bioinformatics research, and this is my first time working with Kaiju. I am trying to build a Kaiju database, but I keep getting errors. The following commands are submitted in a PBS job:
```
kaiju-mkbwt \
-n 1 \
-a ACDEFGHIKLMNPQRSTVWY \ 
-o proteins \ 
proteins.faa

kaiju-mkfmi proteins
```
Then, I get the following output:
```
# infilename= /lustre/marialaura/databases/kaiju/uhgp/renamed_uhpg-90.faa
# outfilename= proteins
# Alphabet= ACDEFGHIKLMNPQRSTVWY
# nThreads= 1
# length= 0.000000
# checkpoint= 5 
# caseSens=OFF 
# revComp=OFF 
# term= * 
# revsort=OFF 
# help=OFF 
Not enough memory allocated for sequence 
# filenm= proteins 
# removecmd= NULL (null) 
# help=OFF 
ERROR: File proteins.bwt containing BWT could not be opened for reading
```
I cannot understand why I get the "not enough memory" error. The server has 96GB of memory allocated for this job. I set the number of threads to 1 in order to use less memory. I have already build a database with a faa file eight times larger (this one has 4.3GB).  Why do I keep getting this error?

Thank you all in advance.

**Comment by premkrishnan** [comment]
Hi Can I check with you, Did you get the solution fro this problem? I am getting this error as well. Thanks in advance.

**Comment by rocpengliu** [comment]
Hello, I have the same error, could you please let me know if you have soloved it?

**Comment by rocpengliu** [comment]
> Hi Can I check with you, Did you get the solution fro this problem? I am getting this error as well. Thanks in advance.

**Comment by premkrishnan** [comment]
Yes I managed to overcome the issue. In my input FASTA file, the sequences were listed in a single line. I reformat this file to 60 characters per line (normal FASTA format). The it worked. So you can try formatting your FASTA file properly and try.

**Comment by rocpengliu** [comment]
> Yes I managed to overcome the issue. In my input FASTA file, the sequences were listed in a single line. I reformat this file to 60 characters per line (normal FASTA format). The it worked. So you can try formatting your FASTA file properly and try.

Hello,
Thank you, I have also find that the format of sequence names seems also can cause this problem. After changing the names, it works.
Thank you again.
