### ISSUE TITLE
kaiju web - direct read annotation

### ISSUE THREAD

**Issue by RitaBogorad** [bioinformatics-centre/kaiju#171]
hello!

I would like to ask if there is a way to get as an output direct tax annotations per read and not a summary of the present in the sample organisms. I tried to link the output from the kaiju.out file with the kaiju.taxonpaths.txt but did not find a mutual ID or index to link between the annotation and the read ID.
Ideally, I would like to have a file where I can see something like this:

Sequence1 Bacteria Proteobacteria _random_bacteria_
Sequence2 Eukaryote Chordata _homo_sapiens_

I have a rather small dataset so I am using the web-server version.

Thank you in advance!

Rita

**Comment by fbucchini** [comment]
Hi, 

I think what you're looking for can be done using the `kaiju-addTaxonNames` command with the `-p` flag to print the full taxon path. Example command:  `kaiju-addTaxonNames -p -i <kaiju_out.tsv> -o <kaiju_out.taxon_names.tsv> -t <nodes.dmp> -n <names.dmp>`

To run this command you'll want to use the same version of the NCBI taxonomy files (`names.dmp` and `nodes.dmp`) used by the webserver. If I recall correctly they can be downloaded under 'Download index'.

**Comment by RitaBogorad** [comment]
thank you very much for your help, that worked flawlessly!:)
