### ISSUE TITLE
Kaiju with 16S dataset?

### ISSUE THREAD

**Issue by LunavdL** [bioinformatics-centre/kaiju#173]
Hi,

I have a 16S amplicon dataset sequenced with Oxford Nanopore Technologies.

I was wondering if anyone has previous experience using Kaiju on a 16S dataset? 
Would the refseq database be appropriate for that? Or the nr database?

Best regards,
Luna

**Comment by pmenzel** [comment]
Hi,

no kaiju is not useful for 16S.

I would just use blastn for ONT 16S sequences.

cheers

**Comment by LunavdL** [comment]
Thank you!
