### ISSUE TITLE
Is there any way to create a krona chart up to the species?

### ISSUE THREAD

**Issue by EulleSA** [bioinformatics-centre/kaiju#175]
Kaiju even ranks the strain, heavily polluting the krona chart when generating. Would there be any way to generate a krona chart up to the species?

Thanks in advance!

**Comment by fbucchini** [comment]
Hi, I think you may want to play with the Krona option themselves (menu on the left), which allows you to control the 'depth' of the chart. You can easily get to more general levels that way!

**Comment by EulleSA** [comment]
The problem I see is that the formatting of the file "* .out.krona", when transformed into ".krona.html", generates a disfigured and confused figure. For example, in this image, I have the taxonomic result shown in KRONA that was generated by two different tools (Kaiju and Basta). The figure generated by the BASTA program shows a more "organized" figure. Is there a way to make the figure more organized like the figure generated by the BASTA tool?

![Screenshot 2021-03-11 112451](https://user-images.githubusercontent.com/22760459/110804447-f1c9c100-825e-11eb-887e-7cf19af2ffa3.png)

**Comment by pmenzel** [comment]
In the latest version of kaiju on github, kaiju2krona now has option `-l` for specifying the ranks that should be included in the krona chart.
