### ISSUE TITLE
Error: Merging results from different databases (nr and nr_euk)

### ISSUE THREAD

**Issue by LeeBergstrand** [bioinformatics-centre/kaiju#176]
Problem Description:
---------------------
I have a metagenomic sample that I want to search for both prokaryotes and eukaryotes and have a combined output showing all life domains (let's say a Krona chart). I scanned the sample using both the `nr` and `nr_euk` databases and their respective `.fmi` files. Note that I used your latest 2021 database release. I then ran `kaiju-mergeOutputs` on the two output files and received the following error.

```
kaiju-mergeOutputs -i S32.nr.out -j S32.nr_euk.out -t nodes.dmp -o S32.out -v
Error: Read names are not identical between the two input files on line 1
Warning: File S32.nr_euk.out has more lines then file S32.nr.out
Number of all reads in input:            1
         classified in file1:            0    0.00%
            but not in file2:            0    0.00%
         classified in file2:            0    0.00%
            but not in file1:            0    0.00%
          classified in both:            0    0.00%
         combined classified:            0    0.00%
```

Notes:
- Kaiju Version = 1.7.4
- Database Version = kaiju_db_nr_2021-02-24.tgz, kaiju_db_nr_euk_2021-02-24.tgz
- I used the nodes.dmp and names.dump from `kaiju_db_nr_2021-02-24.tgz` for `kaiju-mergeOutputs`.
- Kaiju was used with the `-p` flag and protein inputs.

Attempts to Solve:
-------------------

Originally, I thought that the `nodes.dmp` files between `nr` and `nr_euk` had to be merged. However, they have the same MD5 hash and are thus the same.

**Comment by LeeBergstrand** [comment]
Ha ha I just noticed from your docs.

```
The program kaiju-mergeOutputs can merge two tab-separated output files in the column format (see above) used by Kaiju and Kraken. Only the first three columns are used.

The files need to be sorted by the read name in the second column, for example by:

sort -k2,2 kaiju.out  >kaiju.out.sort
sort -k2,2 kraken.out >kraken.out.sort
Then both files can be merged:
```

**Comment by LeeBergstrand** [comment]
You might want to add some text to the above error asking users if they have sorted the two files.

**Comment by LeeBergstrand** [comment]
Are nr and nr_euk the same db? Just that the nr_euk has additional eukaryotic sequences?

**Comment by pmenzel** [comment]
Yes, nr_euk = nr + fungi + microbial eukaryotes.
