### ISSUE TITLE
Is there any way to use shared memory?

### ISSUE THREAD

**Issue by Lix1993** [bioinformatics-centre/kaiju#177]
when annotate multiple fastqs at same time with same db, can memory  be shared between these process

**Comment by Lix1993** [comment]
![kaiju_memory](https://user-images.githubusercontent.com/12579295/112408574-00ca6c00-8d53-11eb-8879-d7847150fec1.png)

**Comment by pmenzel** [comment]
Unfortunately, that is not possible. To reduce the overall memory consumption its probably easier to just do fewer samples with more threads each.

**Comment by Lix1993** [comment]
thanks
