### ISSUE TITLE
Database download

### ISSUE THREAD

**Issue by yuemo98** [bioinformatics-centre/kaiju#178]
Dear Peter

When I run kaiju, I want to use the database of progenomes 2019-02. When I search on the web server, I can only find progenomes 2017-05-16 and progenomes 2020-05-25 and newer versions. Can you provide me with a link to download progenomes 2019-02?  I am looking forward to your reply !

Thanks in advance.

**Comment by pmenzel** [comment]
I found an old progenomes database from 2019-06-25:
you can download it here: http://kaiju.binf.ku.dk/database/kaiju_db_progenomes_2019-06-25.tgz

The link will probably disappear in the near future when I get around to reorganize the web server.

**Comment by yuemo98** [comment]
Thanks for your help!!!!
