### ISSUE TITLE
makedb for mar databases

### ISSUE THREAD

**Issue by softimpulse** [bioinformatics-centre/kaiju#179]
Hi,
i had an issue with downloading source for mar databases. I ran into timeouts. It turns out download links have changed. 
A working hostname is now `public.sfb.uit.no` instead of `s1.sfb.uit.no` and also the starting file path `public/mar` has to be removed.
This has to be done for the files `dl_list*.txt`, all `Current.tsv` and also for the file path inside of the `dl_list*.txt`.
As an example for the mar_ref i did:

 ```
@@ -165,24 +165,24 @@ then
                        if [ "$DB" = "mar" -o "$DB" = "mar_ref" ]
                        then
                                echo Downloading MarRef reference genomes from the Marine Metagenomics Portal
-                               wget -nv -O $DB/dl_list_marref_protein.txt https://s1.sfb.uit.no/public/mar/Resources/kaiju/dl_list_marref_protein.txt
-                               cat $DB/dl_list_marref_protein.txt | xargs -P $parallelDL wget -P $DB/source -q || true
+                               wget -nv -O $DB/dl_list_marref_protein.txt https://public.sfb.uit.no/Resources/kaiju/dl_list_marref_protein.txt
+                               cat $DB/dl_list_marref_protein.txt | perl -p -e 's,s1.sfb.uit.no/public/mar/,public.sfb.uit.no/,' | xargs -P $parallelDL wget -P $DB/source -q || true                                                    
                       fi
```
The change of download path in the source code makes sense but i doubt the patch in the file lists is the way to go, but it was ok for me. I am just the IT guy so i am not sure how to continue from here, i just want to inform you.

**Comment by pmenzel** [comment]
Hi, 
thanks for the info and fix!

@emrobe, are you still working with the mar db? Could you look into fixing the paths in `dl_list_marref_protein.txt` ?

**Comment by emrobe** [comment]
Hi! We are currently making some big changes to our backend. Updates and fixes coming some time after easter, stay tuned :)

**Comment by softimpulse** [comment]
Two more things to mention:

1. Column numbers in MarDB.tsv (https://public.sfb.uit.no/MarDB/Metadatabase/Current.tsv) changed: mmap_ID is now column 104 not 101
 2. There are rows with newline in strings which produced an error in db_map[tokens[104]] = lineage because there are not enough columns (base_ID = 11237 and 14541)

@emrobe, perhaps you can eliminate these newlines before writing?

I fixed both (the latter in a crude way) in `util/kaiju-convertMAR.py`

```[0] % git diff -p                                                                         
diff --git a/util/kaiju-convertMAR.py b/util/kaiju-convertMAR.py
index a83ad77..4106ae7 100644
--- a/util/kaiju-convertMAR.py
+++ b/util/kaiju-convertMAR.py
@@ -72,13 +72,18 @@ def parse_tsv(tsv, db_map=None):
         db_map = dict()
     with open(tsv) as fh:
         # advance beyond header
-        next(fh)
+        line = next(fh)
+        tokens = line.strip("\r\n").split("\t")
+        idx_lineage = tokens.index('taxon_lineage_ids')
+        idx_mmp_ID = tokens.index('mmp_ID')
         for line in fh:
             tokens = line.strip("\r\n").split("\t")
-            # column header: taxon_lineage_ids
-            lineage = tokens[34].rpartition("|")[-1]
+            if len(tokens)<104:
+                line = line + next(fh)
+                tokens = line.strip("\r\n").split("\t")
+            lineage = tokens[idx_lineage].rpartition("|")[-1]
             # column header: mmp_ID
-            db_map[tokens[101]] = lineage
+            db_map[tokens[idx_mmp_ID]] = lineage
     return db_map

**Comment by pmenzel** [comment]
@emrobe I will wait for your pull request :)

**Comment by JuanmaMedina** [comment]
Hello,

First of all, thanks for the implementation and the provisional solutions provided.

I am having some issues with the _makedb_ util and the _mar_ databases. 
Specifically, I have run the command as:
`~/bin/kaiju/bin/kaiju-makedb -s mar`

After fixing both scripts as suggested by @softimpulse, I have found the following error:

_Converting MMP data to Kaiju format
Warnings / Sequences removed:
Duplicates: 0
Accessions with no taxonomic lineage: 0
Accessions with no taxid in nodes.dmp: 0
Sequences with asterix: 0
Creating Borrows-Wheeler transform
# infilename= mar/kaiju_db_mar.faa
# outfilename= mar/kaiju_db_mar
# Alphabet= ACDEFGHIKLMNPQRSTVWY
# nThreads= 40
# length= 0.000000
# checkpoint= 3
# caseSens=OFF
# revComp=OFF
# term= *
# revsort=OFF
# help=OFF
readFasta: No sequences read_

I have been unable to continue the workflow, as I think it is related with the binary c script _kaiju-mkbwt_

I hope this is a useful comment, and if anyone has a potential solution to bypass this, I will highly appreciate it!
:)

**Comment by emrobe** [comment]
Hei. Sorry for this epically late update on this issue, but there is now a working integration of Kaiju towards the Mar-databases new back-end present in my fork at [emrobe/kaiju](https://github.com/emrobe/kaiju)

Two things to keep in mind:
**Firstly**, some of the sequence data needed for Kaiju is not yet available from our back-end. The current situation for kaiju-makedb looks like this:
(MarRef v1.6 "-s mar_ref": 1174 genomes out of 1270 total)
(MarDB v1.5 "-s mar_db": 8501 genomes out of 13237 total)
(Concatenated "-s mar": 9675 genomes out of 14507)
**Secondly**, there is no intuitive way to know what versions of the mardbs you are getting at build time (they are briefly mentioned in an API-string at some point in the script, but that's it). I will have a look at making this a bit more transparent. As mentioned, versions 1.6 and 1.5 for MarRef and MarDB respectively are live right now

@pmenzel I will create a pull request to your repo once the needed data is fully available, and proper versioning of the created dbs are implemented.

(This issue also pertains to issues #193 and #194 )
