### ISSUE TITLE
Wrong size of downloaded index

### ISSUE THREAD

**Issue by 444thLiao** [bioinformatics-centre/kaiju#18]
Yesterday, I am ready to download index from [http://kaiju.binf.ku.dk/server](url) , but today it seem to transfer location to [http://159.226.251.230:80/videoplayer/kaiju_index_nr_euk.tgz?ich_u_r_i=ad3ed0865c98c0c04f7acae0be6268d5&ich_s_t_a_r_t=0&ich_e_n_d=0&ich_k_e_y=1745018910750163332482&ich_t_y_p_e=1&ich_d_i_s_k_i_d=9&ich_u_n_i_t=1](url)

It there are any problems?? May I ask when it can be fixed??

Here my download command.
`wget -c -t 0 http://kaiju.binf.ku.dk/database/kaiju_index_nr_euk.tgz`

Thanks.

**Comment by 444thLiao** [comment]
Transfer location is not the problem, the size of index from 24G become 700M~. I think that must be wrong, so I stop downloading and test several times, it still be there.

**Comment by pmenzel** [comment]
Hi,
I just tried downloading the file and it worked fine and has the correct size as on the server:
```
$ wget -c http://kaiju.binf.ku.dk/database/kaiju_index_nr_euk.tgz
--2017-01-10 10:07:23--  http://kaiju.binf.ku.dk/database/kaiju_index_nr_euk.tgz
Resolving kaiju.binf.ku.dk (kaiju.binf.ku.dk)... 130.226.13.22
Connecting to kaiju.binf.ku.dk (kaiju.binf.ku.dk)|130.226.13.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25450096133 (24G) [application/x-gzip]
Saving to: ‘kaiju_index_nr_euk.tgz’

kaiju_index_nr_euk.tgz                                                 100%[==========================================================================================================================================================================>]  23.70G  7.40MB/s    in 41m 53s 

2017-01-10 10:49:17 (9.66 MB/s) - ‘kaiju_index_nr_euk.tgz’ saved [25450096133/25450096133]
```
No idea why the download stops after 700MB for you.
Make sure that you don't have any proxy servers or something like that in your network.

Peter
