### ISSUE TITLE
wrong file for download nr_euk in https : kaiju_db_nr_euk_2021-02-24.gz should be kaiju_db_nr_euk_2021-02-24.tgz

### ISSUE THREAD

**Issue by Odinidoer** [bioinformatics-centre/kaiju#182]
gz decompress kaiju_db_nr_euk_2021-02-24.gz get a tar file , not 3 correct files, rename to kaiju_db_nr_euk_2021-02-24.tgz and need to run ```tar zxvf kaiju_db_nr_euk_2021-02-24.tgz```

**Comment by pmenzel** [comment]
Not sure what the issue is here?
This should work fine:
```
wget 'https://kaiju.binf.ku.dk/database/kaiju_db_nr_euk_2021-02-24.tgz'
tar xzf kaiju_db_nr_euk_2021-02-24.tgz
```
which should give the three files:
```
kaiju_db_nr_euk.fmi
names.dmp
nodes.dmp
```
