### ISSUE TITLE
No fmi file after refseq installation

### ISSUE THREAD

**Issue by JoaoMBX** [bioinformatics-centre/kaiju#183]
Hi
I trying to install refseq DB, by 
$ kaiju-makedb -s refseq
The process finishes with the creation of nodes.dmp, names.dmp and merged.dmp. In addition, a refseq folder is created which include assembly_summary.archaea.txt, assembly_summary.bacteria.txt and downloadlist.txt,
but I don't see the kaiju_db_refseq.fmi
I tried twice and it's the same.

I can see the problem. Any help?
Thank you

Joao

**Comment by pmenzel** [comment]
Hi Joao,

sounds like some error occurred during index construction. Did you check the output of `kaiju-makedb`?

Also do you have enough RAM on the server for making the RefSeq index, I estimate that 75 GB RAM is required..

**Comment by JoaoMBX** [comment]
Hi
You are right. It was a problem of RAM. I'm working with only 64
Thank you for your help

Joao

**Comment by pmenzel** [comment]
You can also just download a fairly recent kaiju index for RefSeq here: https://kaiju.binf.ku.dk/database/kaiju_db_refseq_2021-02-26.tgz

**Comment by pmenzel** [comment]
I tried building the RefSeq database now, and after download of all bacterial genomes, the program quits on downloading the viral genomes, with:
```
Downloading virus genomes from RefSeq
ftp://ftp.ncbi.nlm.nih.gov/refseq/release/viral/viral.[0-9]*.genomic.gbff.gz:
2021-08-16 18:48:39 ERROR 404: Not Found.
```

**Comment by pmenzel** [comment]
Seems to be that wget globbing only works in FTP mode, but not when wget switches to http due to proxy or something like that.

Alternative is to use curl and http globbing.
