### ISSUE TITLE
error with compiling Kaiju

### ISSUE THREAD

**Issue by Samantha-noel** [bioinformatics-centre/kaiju#187]
Dear Kiaju team

I have encountered a fatal error while compiling the latest version of kaiju
after running
cd kaiju/src
make

resulted in the following

g++ -O3 -pthread -std=c++11 -DNDEBUG -I./include -I./include/ncbi-blast+ -c -o kaiju.o kaiju.cpp
In file included from kaiju.cpp:39:
./include/zstr/zstr.hpp:15:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>

any advice would be appreciated

**Comment by fbucchini** [comment]
Most likely, you don't have the `zlib` library installed on your system. If you're using ubuntu, you can install it using the following: 

```bash
sudo apt-get install libz-dev
```

**Comment by pmenzel** [comment]
Yes, the missing zlib seems to be the problem here.
