### ISSUE TITLE
name.dmp nodes.dmp

### ISSUE THREAD

**Issue by sash2566** [bioinformatics-centre/kaiju#196]
Hi

Can you please share just the names.dmp and nodes.dmp files for the latest version of nr+euk db that you have on the Kaiju webserver?

**Comment by pmenzel** [comment]
see here: https://kaiju.binf.ku.dk/database/taxdump-2021-02-25.tar.gz

**Comment by sash2566** [comment]
Hi again

Thank you for the quick response. 

I was trying to use kaiju2table to get the OTU table from the output of Kaiju webserver. I see that some of the taxids are missing from the file you shared (for example, 998844). Why is that so?

**Comment by pmenzel** [comment]
It is probably due to an accession number in the nr database being still assigned to a taxon id that has been replaced already in the taxonomy. If you are curious, you could unpack the `merged.dmp` file from taxdump.tgz and look for the taxon id there.
