### ISSUE TITLE
Plant database

### ISSUE THREAD

**Issue by valentinavan** [bioinformatics-centre/kaiju#199]
Hi,

I would like to build a custom database for plants. I have downloaded one from UniProt: uniprot_sprot_plants.fa but I am not sure if it contains NCBI taxids for all the proteins (https://beta.uniprot.org/help/taxonomic_identifier). 
1) Can I use the nodes.dmp and names.dmp (extracted from NCBI taxdump.tar.gz) together with uniprot_sprot_plants.fa to build a custom kaiju database?
2) Are nodes.dmp and names.dmp "universal" for all the NCBI databases? 

Thanks in advance

**Comment by pmenzel** [comment]
Hi,

If you want to make a database from a custom fasta file, you need to follow the [file format](https://github.com/bioinformatics-centre/kaiju#custom-database).

Did you consider to just use the plant sequences from the NCBI BLAST nr database? Then it is just a matter of adding the proper taxon IDs to `bin/kaiju-taxonlistEuk.tsv` and run `kaiju-makedb -s nr_euk`.

**Comment by valentinavan** [comment]
Thanks Peter,

I have done how you told me to do but I have problems in downloading again nr_euk. I have tried two times and I get the same error. 
I have a Mac Pro (2019) 16 cores, 192 GB of memory. 
It successfully dowloaded nodes.dmp, names.dmp, merged.dmp and in the nr_euk folder there are nr.gz, prot.accession2taxid, prot.accession2taxid.gz. 
The .fmi file is missing.
Can you please help me to understand where the problem is? 
Thanks 

<img width="1629" alt="Screen Shot 2021-11-17 at 9 48 53 AM" src="https://user-images.githubusercontent.com/63851352/142089343-f74d4fd0-8bb7-4ab9-a79a-0706ea9577b3.png">

**Comment by pmenzel** [comment]
Looks like the file prot.accession2taxid.gz is broken and cannot be uncompressed. I just downloaded and uncompressed it, and it didn't see any error. In principle it should not be due to using MacOS. btw, do the kaiju binaries run fine on MacOS? I didn't try it for many years..

**Comment by valentinavan** [comment]
Hi Peter,

So far I have not had any issue running Kaiju on my Mac computer.

In relation to the problem I have, after browsing on the internet around I have found a possible solution (https://www.biostars.org/p/9488508/#9488529   last comment): 
I substituted ftp:// with http:// and re-downloaded prot.accession2taxid.gz and unzipped it, which gave me prot.accession2taxid without problem...but now I do not know what to do with this file....how can I create a new updated .fmi file? Thanks

**Comment by pmenzel** [comment]
Great, then you just need to put `prot.accession2taxid.gz` into the `nr_euk/` folder and add the argument `--no-download` to `kaiju-makedb`. It will be unzipped again by the script, but that should not matter.

**Comment by valentinavan** [comment]
Great! 
However after running <kaiju-makedb -s nr_euk --no-download> I got:
kaiju_db_nr_euk.faa, kaiju_db_nr_euk.sa, kaiju_db_nr_euk.bwt but not the .fmi still. 

So, I have tried running <kaiju-mkbwt -n 5 -a ACDEFGHIKLMNPQRSTVWY -o kaiju_db_nr_euk PATH/nr_euk_updated/nr_euk/kaiju_db_nr_euk.faa> but it seems stuck...what should I do to obtain the .fmi file? Thanks!

**Comment by valentinavan** [comment]
EDIT:  I run 
<kaiju-mkfmi PATH/nr_euk_updated/nr_euk/kaiju_db_nr_euk>
and now I finally got the .fmi file :)

**Comment by valentinavan** [comment]
EDIT2: I have tried running kaiju using the updated database but its not working. it says "segmentation fault" and create empty output files....

**Comment by valentinavan** [comment]
Hi,

Can someone please help me out to figure out where the issue is with the "segmentation fault" error message?

Thanks

**Comment by pmenzel** [comment]
Segmentation fault when running `kaiju-mkfmi` usually indicates that there is not enough available RAM.
See [the table here](https://github.com/bioinformatics-centre/kaiju#creating-the-reference-database-and-index) about memory requirements. When adding additional taxa to the nr_euk database, then expect even higher memory requirements.

**Comment by valentinavan** [comment]
Hi Peter,

`kaiju-mkfmi ` worked well, I think, because I got all the files I needed. 

I got the "segmentation fault" message after running the kaiju alignment to my samples (in loop: kaiju + kaiju2krona + kaiju2table + ktImportText). I also got empty outputs.

**Comment by pmenzel** [comment]
Hi,

can you paste the kaiju command that failed and what kaiju prints to the terminal?

**Comment by valentinavan** [comment]
Hi Peter thanks a lot for helping me out.

This is the script I have been always using without any problem til I used this "updated" db.

```
#!/bin/csh -x

set DATADIR= path/fastq_minion
set DATAOUT=path/kaiju_nreuk_plants
set DATABASEDIR= path/kaijudb/nr_euk_updated
set DATABASE=path/kaijudb/nr_euk_updated/nr_euk/kaiju_db_nr_euk.fmi

foreach INPUT (BA0_CoTr OG0_CoTr ON0_CoTr ON1_CoTr ON11_CoTr ON2_CoTr ON3_CoTr ON4_CoTr ON5_CoTr ON6b_CoTr ON7_CoTr ON8_CoTr SB2_CoTr SJ1_CoTr)

set INPUT_i=${INPUT}.fastq.gz

kaiju -t ${DATABASEDIR}/nodes.dmp -f ${DATABASE} -z 8 -i ${DATADIR}/${INPUT_i} -o ${DATAOUT}/${INPUT}.out

kaiju2krona -t ${DATABASEDIR}/nodes.dmp -n ${DATABASEDIR}/names.dmp -i ${DATAOUT}/${INPUT}.out -o ${DATAOUT}/${INPUT}.out.krona

kaiju2table -t ${DATABASEDIR}/nodes.dmp -n ${DATABASEDIR}/names.dmp -r species -l superkingdom,phylum,class,order,family,genus,species -o ${DATAOUT}/${INPUT}_ALL.tsv ${DATAOUT}/${INPUT}.out

ktImportText -o ${DATAOUT}/${INPUT}_prg.html ${DATAOUT}/${INPUT}.out.krona

end 
```

This is an example of what it prints out:

```
set INPUT_i=BA0_CoTr.fastq.gz
kaiju -t /Users/linnaeus/kaijudb/nr_euk_updated/nodes.dmp -f /Users/linnaeus/kaijudb/nr_euk_updated/nr_euk/kaiju_db_nr_euk.fmi -z 8 -i /Users/linnaeus/caves/ALL_CAVES/fastq_minion/BA0_CoTr.fastq.gz -o /Users/linnaeus/caves/caves_ont/kaiju_nreuk_plants/BA0_CoTr.out
Segmentation fault

kaiju2krona -t /Users/linnaeus/kaijudb/nr_euk_updated/nodes.dmp -n /Users/linnaeus/kaijudb/nr_euk_updated/names.dmp -i /Users/linnaeus/caves/caves_ont/kaiju_nreuk_plants/BA0_CoTr.out -o /Users/linnaeus/caves/caves_ont/kaiju_nreuk_plants/BA0_CoTr.out.krona

kaiju2table -t /Users/linnaeus/kaijudb/nr_euk_updated/nodes.dmp -n /Users/linnaeus/kaijudb/nr_euk_updated/names.dmp -r species -l superkingdom,phylum,class,order,family,genus,species -o /Users/linnaeus/caves/caves_ont/kaiju_nreuk_plants/BA0_CoTr_ALL.tsv /Users/linnaeus/caves/caves_ont/kaiju_nreuk_plants/BA0_CoTr.out

ktImportText -o /Users/linnaeus/caves/caves_ont/kaiju_nreuk_plants/BA0_CoTr_prg.html /Users/linnaeus/caves/caves_ont/kaiju_nreuk_plants/BA0_CoTr.out.krona
Writing /Users/linnaeus/caves/caves_ont/kaiju_nreuk_plants/BA0_CoTr_prg.html...

end
```

The output files produced are all empty. Interestingly, all the tables look like this one:
<img width="820" alt="Screen Shot 2021-12-10 at 10 53 54 AM" src="https://user-images.githubusercontent.com/63851352/145504075-8cce14c3-c763-4684-b890-0d62ec772246.png">

The modified database folders are these ones:
<img width="1605" alt="Screen Shot 2021-12-10 at 10 57 02 AM" src="https://user-images.githubusercontent.com/63851352/145504702-616095c7-2881-4d2b-9da2-165a1e357bb4.png">

And the file` bin/kaiju-taxonlistEuk.tsv `contains the added taxa as you told me to do previously. 

Hope you can find where the problem is! 

Thanks!

**Comment by valentinavan** [comment]
.btw and .sa files are zero bytes. 
.faa is 110,23 GB
.fmi is 92 bytes.
Looks like something is wrong with this files then :(

**Comment by pmenzel** [comment]
Yes, they should be some gigabytes. Since you already got the .faa file, you could restart your kaiju-makedb with the option `--index-only` and it will just build the index from the .faa file. Check the output for any error messages, I suspect that you need more RAM than what is available. In March, kaiju-makedb needed 222GB or RAM for the standard nr_euk database.

**Comment by valentinavan** [comment]
Hi Peter,

I have run kaiju-makedb -s nr_euk --index-only but still: 

.btw and .sa files are zero bytes.
.faa is 110,23 GB
.fmi is 92 bytes.

I have 192 GB of RAM. I guess there is no solution then.

**Comment by valentinavan** [comment]
This is what it printed:

nr_euk_updated % kaiju-makedb -s nr_euk --index-only
Extracting taxdump.tar.gz
Unpacking prot.accession2taxid.gz
Creating BWT from Kaiju database
# infilename= nr_euk/kaiju_db_nr_euk.faa
# outfilename= nr_euk/kaiju_db_nr_euk
# Alphabet= ACDEFGHIKLMNPQRSTVWY
# nThreads= 5
# length= 0.000000
# checkpoint= 5
# caseSens=OFF
# revComp=OFF
# term= *
# revsort=OFF
# help=OFF
Sequences read time = 4801.196458s
SLEN 106716750644
NSEQ 280049653
ALPH *ACDEFGHIKLMNPQRSTVWY
/Users/linnaeus/opt/anaconda3/envs/bioinfo/bin/kaiju-makedb: line 224: 20689 Bus error: 10           kaiju-mkbwt -e $exponentSA_NR -n $threadsBWT -a ACDEFGHIKLMNPQRSTVWY -o $DB/kaiju_db_$DB $DB/kaiju_db_$DB.faa

**Comment by pmenzel** [comment]
If memory is the limiting factor, you could also make two databases instead of one:
* the standard nt database
* an nr_euk database where you add your plants,  and remove bacteria/Archaea and viruses (first three lines in kaiju-taxonlistEuk.tsv)

Build them separately and see if you can run them individually. If so, then run each sample through both databases and use `kaiju-mergeOutputs -s` to merge the output files into one.

**Comment by valentinavan** [comment]
Hi Peter, 

sorry for all these questions and if I seem confused but I am learning this field on the go. 

Another option could be this:
I have downloaded the fasta files of these plants from the NCBI so I could also build a custom db using `kaiju-mkbwt` and `kaiju-mkfmi`. 
But these are genomes and not proteins. Indeed, for some taxa the protein fasta file is not available. 
The genome fasta files look like this:
```
>QAOD01000001.1 Alnus glutinosa isolate NF-2018-1 scaffold112333_cov55, whole genome shotgun sequence
TTTGATATAGAAGATACAATTCAGTTTTCCATTGAAAGTTCTCTAAGTAGTGATGACTACTTCTTGGTGTGACGCCAAGA
TTTCTGGTGTGACTCCAGAATTCTTCAAGTTACGATTGTGTTGCGTCATTCATTTTTGAACCTCATCATCCACACTCAAG
ATTACAATGAGCAACTACATATACAATTGTCACAAATCGCTAGCATTAAGGAACTAAGACAAacccaatataaaaaattg
acccATTTAAG
>QAOD01000002.1 Alnus glutinosa isolate NF-2018-1 scaffold47950_cov44, whole genome shotgun sequence
TCAGCAATCCCAAAAGGAGATATATAGAAATTTATGACTAGCTACTTATATTCATAAGAGGTTAATTATATCTTTTagaa
atgagtaatgttatttatacGATTACCATTTAACTTAATAATATAATAGTGAAAATTAGCCTCTGAATTaatacttggaa
aaaaaaaaaaggagcaaaataacaaaataaccaAAGACTTGTTAGCTGATTTTCATTGCTTCGTCAACTCAGTTGAATGA
CGGCcgacaatctactaaatagcattaacTTTGTATATATAGAATTTTTCCAAAAGATCA
```
Could it work with these files? Can I mix proteins and genomes fasta files?

If it is not possible I will build the db with just the taxa that I can download protein fasta files of.

Thanks a lot!! I do not have nobody to ask for help here.

**Comment by pmenzel** [comment]
Hi,

kaiju only does protein sequences. You could try the program kraken2 to make a custom database for nucleotide sequences. That should also work fine.

**Comment by valentinavan** [comment]
Yes, I did and it seems to work fine however it also produced a text file with a long list of unmapped accession numbers and I do not know how to treat it (for example I cannot find out what taxa have been finally included in the db). I have asked for help in this platform and in Biostars and hope that someone can help.

Now, I am also trying to re-build the kaiju nr_euk modified db using an external server with more memory and hopefully I will be successful this time.

Thanks Peter for your help
