### ISSUE TITLE
Refseq with eukaryotes

### ISSUE THREAD

**Issue by sash2566** [bioinformatics-centre/kaiju#200]
As I understand the prebuilt refseq for kaiju does not have eukaryotic sequences in it. Is there a way to generate a complete refseq database for analyses using kaiju?

**Comment by pmenzel** [comment]
In principle one could probably modify the `refseq`-section of kaiju-makedb and download the file https://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt instead of the files for bacteria/Archaea and process it in a similar way.
I never tried it though.
