### ISSUE TITLE
Virus classification without genus

### ISSUE THREAD

**Issue by steinbrl** [bioinformatics-centre/kaiju#202]
I tried kaiju with different databases (viruses, refseq, progenomes+virus). The classification of bacterial reads is flawless, but all virus reads are summarized in "Viruses". Independent whether I use genus or species or something else, I only get the classification "viruses", but no taxonomy. How can I solve this problem?

Greetings,

Lars
[kaiju_kreport.csv](https://github.com/bioinformatics-centre/kaiju/files/7642346/kaiju_kreport.csv)

**Comment by pmenzel** [comment]
Hi,

you can try adding option `-e` to `kaiju2table`.

**Comment by steinbrl** [comment]
it worked, thanks a lot !
