### ISSUE TITLE
 classification for some interesting functional genes

### ISSUE THREAD

**Issue by laibinhuang** [bioinformatics-centre/kaiju#205]
Hi Kaiju team:

It is possible to get the classification for some interesting functional genes:

I want to know both the abundance and the classification for AOA, AOB, nirK/S, and nosZ; wonder how can I do this using the kaiju pipeline.

thank you

**Comment by pmenzel** [comment]
Kaiju is not the ideal tool for this out of the box. I suggest to make a metagenome assembly and search it for your favorite genes.
