### ISSUE TITLE
Unable to install in MacOS Monterey

### ISSUE THREAD

**Issue by biotemon** [bioinformatics-centre/kaiju#206]
cd kaiju/src
make

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C bwt/ 
gcc -O3 -g -Wno-unused-result -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/tito_miniconda/opt/miniconda3/include  -c -o mkbwt.o mkbwt.c
In file included from mkbwt.c:59:
/usr/local/lib/gcc/x86_64-apple-darwin18.5.0/8.3.0/include-fixed/stdio.h:78:10:fatal error: _stdio.h: No such file or directory
 #include <_stdio.h>
          ^~~~~~~~~~
compilation terminated.
make[1]: *** [mkbwt.o] Error 1
make: *** [bwt/mkbwt] Error 2

**Comment by pmenzel** [comment]
Maybe you need to install the development files for the C standard library?

**Comment by biotemon** [comment]
I tried several forums. Nothing worked. I ended installing kaiju in a ubuntu virtual box in my mac machine. I believe kaiju is still MacOS Monterey incompatible.
