### ISSUE TITLE
Probems when using kaiju2table for the out_file from nr_euk database

### ISSUE THREAD

**Issue by zhuyiqing666** [bioinformatics-centre/kaiju#207]
HI Kaiju team,

I received the following error when running kaiju2table.
Warning: Taxon ID 998844 is not contained in ../nr_euk/nodes.dmp.

How can a taxon ID be missing from the nodes.dmp file when it was the same file used to run kaiju? How to address it? I used the nr_euk database.

Thanks
Nana

**Comment by pmenzel** [comment]
Hi,

you can ignore those warnings. The nr database sometimes contains entries with outdated taxon IDs that are used in the kaiju index, which was fixed here https://github.com/bioinformatics-centre/kaiju/commit/7ed82d1cafb377dad33b7117b504f1cf602fae83, but the downloadable indizes still have this issue.
