### ISSUE TITLE
Building the nr database with low RAM

### ISSUE THREAD

**Issue by TakacsBertalan** [bioinformatics-centre/kaiju#212]
Hi!
I would like to use kaiju with the nr database, but I only have access to 12 processor threads and 62 GB of RAM. Is there a way to still build this database? Would dividing the nr.gz file into chunks and building the separately be a possible solution? Or should I just give up on nr and use a less extensive database?

Thanks,
Bertalan Takacs

**Comment by pmenzel** [comment]
Hi,

you could certainly divide the nr file up into chunks and make one database from each one.  
Look here for the necessary steps: https://github.com/bioinformatics-centre/kaiju/blob/master/util/kaiju-makedb#L225

Next, classify your reads against each of those databases and merge the separate output files with kaiju-mergeOutputs.

You could also upload your samples to the kaiju web server.

best,
Peter
