### ISSUE TITLE
Segmentation fault (Core dump)

### ISSUE THREAD

**Issue by FelipeMSD** [bioinformatics-centre/kaiju#216]
Dear all,

I am submitting this SGE job array to align 1041 fastq files with a custom database made from a fasta file with NCBI taxon IDs as headers:

#!/bin/bash
#$ -cwd
#$ -N kaiju_sd_taxa_v1
#$ -e /error_folder/kaiju_sd_taxa/$JOB_NAME-$JOB_ID-$TASK_ID.err
#$ -q short-sl7
#$ -l virtual_free=20G,h_vmem=20G
#$ -pe smp 4
#$ -t 1-1041

INPUT=$(ls input_folder/no_host/*R1_nohost.fastq.gz | sort -u | sed -n ${SGE_TASK_ID}p)
I=$(echo $INPUT | sed 's/1_nohost.fastq.gz//')
O=$(echo $I | sed -r 's/.{52}//' | sed 's/_R//')
REF="/ref_folder/indexes/kaiju/sd_taxa/"
OUT="/output_folder/kaiju_sd_taxa/"

conda activate taxon
kaiju -z $NSLOTS -t ${REF}nodes.dmp -f ${REF}sd_protein_index_tax.fmi -i ${I}1_nohost.fastq.gz -j ${I}2_nohost.fastq.gz -v -o ${OUT}out_files/${O}.out

However, I keep getting the segmentation fault (core dump) error message on my log file:

20:11:41 Reading database
 Reading taxonomic tree from file /ref_folder/indexes/kaiju/sd_taxa/nodes.dmp
 Reading index from file /ref_folder/indexes/kaiju/sd_taxa/sd_protein_index_tax.fmi
Output file: /output_folder/kaiju_sd_taxa/out_files/00077E64B3_S922_L003.out
20:11:45 Start classification using 4 threads.
/cluster/node-hp0410/job_scripts/78723012: line 20: 28938 Segmentation fault      (core dumped) kaiju -z $NSLOTS -t ${REF}nodes.dmp -f ${REF}sd_protein_index_tax.fmi -i ${I}1_nohost.fastq.gz -j ${I}2_nohost.fastq.gz -v -o ${OUT}out_files/${O}.out

In the past I used this script to align the same fastq files with a reference database made from progenomes, which is bigger than the database I have now, and it worked with only 1 core and 20G of free memory.

These are the first lines of the fasta file I used to build my custom .fmi reference db:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/92450293/158679483-cd875c9a-f5c4-4f55-accd-0e6092ce1aa3.png">

Do you have any insights on what I might do to fix it?

Kind regards,
Felipe

**Comment by FelipeMSD** [comment]
Hi Peter!

That were very good tips! I searched the other letters "BJOUXZ" and in fact there were some "Xs" on the fasta file. In this case, should I remove them on the file or should I include "X" as one of the letters when I build the reference db again?

**Comment by pmenzel** [comment]
I normally just remove them from the database as they will anyway not occur in a translated protein query, i.e. the database search will stop at these positions. Also adding more characters will make the index larger.

**Comment by FelipeMSD** [comment]
It worked! Thank you very much!

**Comment by pmenzel** [comment]
Yeah that sounds weird :)

Maybe it was an issue with the line endings? They should be the newline character (LF, ascii 0A) only.

**Comment by FelipeMSD** [comment]
I used `sed 's/ //g'`to remove all spaces in my fasta file with headers like this  `>2320122` (only 1 NCBI taxon ID) and still cannot build the index ("Not enough memory allocated for sequence")...

**Comment by pmenzel** [comment]
what is the length of the longest sequence in your input file?

can you send me the file?

**Comment by FelipeMSD** [comment]
Let me know if you were able to access the file here: https://drive.google.com/file/d/1hTf56BYnc9Q14wzQkUgJ1Erty2l_6lcy/view?usp=sharing

**Comment by pmenzel** [comment]
```
seqkit stats rat_geneset_protein_v4_taxid.faa                                                                                                                                                                                                                                                        file                              format  type      num_seqs        sum_len  min_len  avg_len  max_len
rat_geneset_protein_v4_taxid.faa  FASTA   Protein  4,566,714  1,207,935,467       21    264.5   40,218
```
Ok, that it explains it. The maximum length of sequences for kaiju-mkbwt is 10000.
Better to remove this long sequence.

**Comment by FelipeMSD** [comment]
I used `seqkit seq -M 10000 rat_geneset_protein_v4_taxid.faa.gz -o rat_geneset_protein_v5_taxid.faa` to remove all sequences with more than 10k amino acids and ran kanji-mkbwt again and it worked. However, when I use the code from the first post to align this index with my fast files the core dump error strikes again.

**Comment by pmenzel** [comment]
There were still some characters outside the allowed alphabet in your file.
You can remove them like this:
```
perl -lpe 's/[^ACDEFGHIKLMNPQRSTVWY]//g unless /^>/' rat_geneset_protein_v5_taxid.faa > rat_geneset_protein_v5_taxid_filter.faa
```

**Comment by FelipeMSD** [comment]
Good catch! I didn't know I could find these other characters. Thank you very much! Now it's working ;)

**Comment by FelipeMSD** [comment]
Dear Peter,

I am trying to make a new Kaiju index from a fasta file with 200.5M protein sequences and I had already:

1. Removed undesired characters;
2. Split sequences that were longer than 9k aa;
3. Broken all sequences in lines with 60aa each

However, I keep having the "Segmentation fault (core dumped)" error when I run "kaiju-mkbwt -n $NSLOTS -a ACDEFGHIKLMNPQRSTVWY -o out_file in_file", even using 8 threads with 20G of free memory, each. Is there something else I might be doing wrong?

Kind regards,
Felipe

**Comment by FelipeMSD** [comment]
Dear Peter,

I am trying to make a new Kaiju index from a fasta file with 200.5M protein sequences and I had already:

Removed undesired characters;
Split sequences that were longer than 9k aa;
Broken all sequences in lines with 60aa each
However, I keep having the "Segmentation fault (core dumped)" error when I run "kaiju-mkbwt -n $NSLOTS -a ACDEFGHIKLMNPQRSTVWY -o out_file in_file", even using 8 threads with 20G of free memory, each. Is there something else I might be doing wrong?

Kind regards,
Felipe

**Comment by pmenzel** [comment]
Hi,
that usually means that the process ran out of memory. Do you have any means of observing the memory usage?

According to the table in the README, I needed 259GB or RAM to build the nr database with 249M sequences.
So maybe your 160GB is still too small..

**Comment by FelipeMSD** [comment]
Thank you, Peter! It worked. The problem now is that they keep killing the job on the cluster... Let's see if I can finally run it.

Cheers,
Felipe

**Comment by FelipeMSD** [comment]
Hi Peter,

I was able to build a kaiju index from a fasta file almost with the same size as NCBI nr, but now, when I try to run kaijux in order to align my paired reads to this index some of my files get the "Segmentation fault (core dump)" error and some are just "Killed" by the cluster. Do you have any tip on how I can manage that? Could this be a problem with the index?

Kind regards,
Felipe

**Comment by FelipeMSD** [comment]
Never mind, I've made few tests and the index is fine. It's just a matter of finding the best balance of free memory and cores ;)
