### ISSUE TITLE
Low rates for genus and family assignments

### ISSUE THREAD

**Issue by FelipeMSD** [bioinformatics-centre/kaiju#219]
Dear Peter,

I aligned my fastq files with 3 different reference catalogues (Progenomes and 2 custom DB) and for all of them I always have better assignment rates for species than for genus and family. I expected that the assignment rates would be lower going down on the taxonomic tree, given that if I assign a taxa for a certain level, automatically I know what the upper levels are. Do you know why this pattern might be happening for Kaiju?

I'm sharing the rates I had for Progenomes, so you can have an idea:

  | average assignment rate per sample
-- | --
phylum | 99%
class | 90%
order | 90%
family | 75%
genus | 63%
species | 81%

**Comment by pmenzel** [comment]
Great Question!  
My first guess is that the difference is made up of genomes that belong to species that have just a provisional place in the NCBI taxonomy. For example [Enterobacterales bacterium 8AC](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=2653184&lvl=3) (which is the species name) has no assigned genus or family, just the order Enterobacterales, and there are many of such species, see e.g. [here](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=91347&lvl=3)

Maybe the proGenomes database also contains such genomes.

**Comment by FelipeMSD** [comment]
I haven't noticed that. Thank you very much!

**Comment by pmenzel** [comment]
Another example is the genus [Thiomonas](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=32012&lvl=3&lin=f&keep=1&srchmode=1&unlock), which is not assigned to a family.

**Comment by FelipeMSD** [comment]
Now that you called my attention to that I cannot stop seeing them all over my data haha.
