### ISSUE TITLE
Segmentation fault (core dumped), I have read some issues document before and didn't find a good solution

### ISSUE THREAD

**Issue by yuzie0314** [bioinformatics-centre/kaiju#222]
Dear Kaiju authors,
I used your tool to annotate my contigs (human fecal metagenome samples, went through assembly and binning), and confronted such error.
My command: kaiju -t /kaiju_db/nodes.dmp -f /kaiju_db/kaiju_db_nr.fmi -i *.fa -z8 -o kaiju.out.txt Segmentation fault (core dumped)
I have tried several time, so I think if my bins are too long to be annotated or there is anything wrong with my command?
My available ram is about 64 Gb, and I think it's enough for Kaiju to run ?

Thanks in advance !
Regards,
Yuzie

**Comment by pmenzel** [comment]
Hi,

64GB RAM is not enough for the nr database, have a look at the table [here](https://github.com/bioinformatics-centre/kaiju#creating-the-reference-database-and-index)

**Comment by pmenzel** [comment]
Yes.
