### ISSUE TITLE
Little doubt about taxid codes used by Kaiju proGenomes v2.1 database

### ISSUE THREAD

**Issue by magibc** [bioinformatics-centre/kaiju#225]
Hi Kaiju's developer Dr. Peter Menzel @pmenzel  and also all the Kaiju's community.

Some months ago, from a shotgun metagenomic study I performed a taxonomical classification with Kaiju with success  using proGenomes v2 downloaded on March 2022:

Summary of the commands executed:

```

kaiju \
    -t ${db}/nodes.dmp \
    -f ${db}/kaiju_db_progenomes.fmi \
    -i $forward \
    -j $reverse \
    -o ${id}.kaiju.out \
    -z 8

kaiju2table \
-t ${db}/nodes.dmp \
-n ${db}/names.dmp \
-r species \
-o ./output_kaiju2table/${id}.kaiju.species_report.tsv ${id}.kaiju.out \
-l superkingdom,phylum,class,order,family,genus,species
```

Then I merged all kaiju.species_report.tsv.

Finally, I discovered a strategy to construct a phylogenetic tree from Kaiju results.

The taxid codes used for proGenomes could be find on:  https://progenomes.embl.de/data/proGenomes2.1_specI_lineageNCBI.tab.

However for my 2034 species classified by Kaiju, there are 5 species and therefore 5 NCBItaxonID that does not appear in the previous file: proGenomes2.1_specI_lineageNCBI.tab and, as consequence, also not appears in proGenomes2.1_markerGenes.tar.gz (used for tree construction)

The five species are:

NCBI_TaxonID    Taxa_name
2585118             Alistipes communis

2044587               Schaedlerella arabinosiphila;

2652292               Hornefia porci

2093824                Candidatus Nanosynbacter lyticus

1712410                Thermoanaerosceptrum fracticalcis

I've checked for updates in NCBI taxonomy browser if this species have been updated  to a new NCBI taxid code but I do not find.

Before to remove this 5 species, I decided to post this simple doubt here If I can solve this problem and taking into account this species.

Thanks on advance,

Magí

**Comment by pmenzel** [comment]
It seems to be a mismatch between the files that proGenomes provides, then I don't know how that can be fixed..

**Comment by magibc** [comment]
Ok thank you Peter another time for your response. I would try to put into contact with proGenomes developers.
