### ISSUE TITLE
error with make Kaiju, Help...

### ISSUE THREAD

**Issue by paola190** [bioinformatics-centre/kaiju#226]
Hello 
 
I installed kaiju with 
**git clone https://github.com/bioinformatics-centre/kaiju.git,**
and then I installed  
**sudo apt-get update -y
sudo apt-get install -y libz-dev**
However, in the step 
**cd kaiju/src
make**

I found a error 
micromoluser@EMIC145363 ~/kaiju/src
$ make
make -C bwt/
make[1]: Entering directory '/home/micromoluser/kaiju/src/bwt'
gcc -O3 -g -Wno-unused-result -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/micromoluser/miniconda3/envs/bioinfo/include  -c -o mkbwt.o mkbwt.c
**make[1]: gcc: No such file or directory
make[1]: *** [<builtin>: mkbwt.o] Error 127
make[1]: Leaving directory '/home/micromoluser/kaiju/src/bwt'
make: *** [makefile:45: bwt/mkbwt] Error 2**
(bioinfo)

**Comment by paola190** [comment]
@pmenzel Thankss

**Comment by pmenzel** [comment]
Well, it looks like you are missing the C/C++ compiler gcc on your system.
If you are using ubuntu, try installing the meta-package named “build-essential”.

**Comment by paola190** [comment]
Hello @pmenzel. Thanks for your answer. I install build-essential and kaiju was compiled. 
Thanks.
