### ISSUE TITLE
resume/continue

### ISSUE THREAD

**Issue by Mewgia** [bioinformatics-centre/kaiju#228]
Hi!
Is it possible in kaiju to continue the classification interrupted? For example, the classification is being recorded and suddenly the electricity is turned off. Naturally, the computer shuts down, and what should we do?
Of course, you can say "buy an external power supply", but what to do in case of prolonged absence of electricity? That is, I want to know if it is possible to continue writing to an already existing file, rather than starting all over again.
Thanks.

**Comment by pmenzel** [comment]
No. You would need to start over again.
