### ISSUE TITLE
Problem with the latest version (1.9.0)

### ISSUE THREAD

**Issue by valentinavan** [bioinformatics-centre/kaiju#231]
Hi,

I have recently updated Kaiju on my Mac. Now it is not working anymore and If I download the conda version (it is an old one) many files are missing in the bin folder, like kaiju2table so is not working neither this version. 

This is the error I get with the latest version:

`kaiju: /mnt/lustre/home/valentina/miniconda3/envs/kaiju/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by kaiju)`

Thanks

**Comment by pmenzel** [comment]
did you get v1.9.0 also via `conda install`? 
It sounds like the conda package was not build properly..

**Comment by valentinavan** [comment]
Apologies, it was an obvious question. Some of the conda links seem to have some missing files. 

I re-downloaded it using `git clone https://github.com/bioinformatics-centre/kaiju.git` and it works fine now.

Thanks
