### ISSUE TITLE
Run makeDB.sh again when it fails

### ISSUE THREAD

**Issue by koopkaup** [bioinformatics-centre/kaiju#24]
I had a problem when extracting protein sequences:
```
Can't locate IO/Uncompress/AnyUncompress.pm in @INC (@INC contains: /storage/software/perl-5.22.0/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /gpfs/hpchome/a51256/bin/gbk2faa.pl line 15.
BEGIN failed--compilation aborted at /gpfs/hpchome/a51256/bin/gbk2faa.pl line 15.
```

I made some changes and rerun makeDB.sh, but it started to download all genomes again (RefSeq). Is it possible to make this script check first if all genome files have been downloaded and then skip this step?

Kristjan

**Comment by pmenzel** [comment]
You can use option `--noDL` for makeDB.sh to skip downloading and use the files that are already there.

Also I put a check into makeDB.sh to test if AnyUncompress.pm is available.. seems like it didn't work there...

Peter
