### ISSUE TITLE
`-a greedy`: `-a` must be a valid mode.

### ISSUE THREAD

**Issue by ebete** [bioinformatics-centre/kaiju#241]
Running kaiju with `-a greedy` gives an exception:
```
-a must be a valid mode.
Kaiju 1.9.0
. . .
```

`greedy` clearly is a valid mode:
https://github.com/bioinformatics-centre/kaiju/blob/591302244a95e8410e5f8df2b95bc21392611e0d/src/kaiju.cpp#L436

But here it only allows `mem`:
https://github.com/bioinformatics-centre/kaiju/blob/591302244a95e8410e5f8df2b95bc21392611e0d/src/kaiju.cpp#L76-L83

Either the help text needs to be updated or the `-a greedy` parameter should not throw an error.

**Comment by pmenzel** [comment]
Hi, thanks for reporting.

I will fix the option parsing. Even so `greedy` is the default mode, it should also be possible to explicitly set it!
