### ISSUE TITLE
Sementation fault using March 2022 databases

### ISSUE THREAD

**Issue by skgs1970** [bioinformatics-centre/kaiju#242]
Hi, 
I ran 3 samples on the webserver and got the results yesterday. I wanted to make tables and graphs and diversity calculations so I downloaded the latest nr_euk(March 2022) and realized it gave many TAXON_ID not found messages when I tried to get the summary. 
I had read some earlier threads where you suggested using the files(*.fmi, *.dmp) that the webserver uses.  I have downloaded them, but since that database is at least a year old, I thought I would run using the latest database locally.
So I tried to run the samples on our cluster and it keeps giving segmentation fault on all the options-5 threads, 25 threads and no threads option. We have  36 processors on each node with 128 Gb of RAM and I used 3 nodes to speed up the process. Even while running on the head node I got the same segmentation fault and core dump. The core dump is not stored in my area so I can't see it. 

This is the command I wrote

out=~/Fastq/kaiju_out

~/kaiju/bin/kaiju -z 5 ~/kaijudb/nodes.dmp -f ~/kaijudb/kaiju_db_nr_euk.fmi -i ~/Fastq/E_R1.AdaptTrimmed2.fastq.gz -j ~/Fastq/E_R2.AdaptTrimmed2.fastq.gz  -o $out/E.out

Am I missing something? And is there another way to make graphs, tables, diversity etc.. using the output from the web server.

Thankyou,
Suresh

**Comment by pmenzel** [comment]
128 GB of RAM is not enough for the nr_euk database, even for the one from 2021 that is used by the web server.

You can download the file https://kaiju.binf.ku.dk/database/kaiju_db_nr_euk_2021-02-24.tgz and extract it. It contains the correct names.dmp and nodes.dmp files, that you can use locally for kaiju2table on the output files from the web server, for example.

**Comment by skgs1970** [comment]
Thankyou for the prompt reply. I will do that. I too thought 128GB may not be sufficient, so I used 3 nodes, that is 108 processors and 384Gb, is this not sufficient?. Sorry I am just an user and not very well versed in HPC usage, was I wrong in assuming that it will provide 384GB of RAM. 
By the way can you recommend any suitable programs for publication quality graphs from the data.

**Comment by pmenzel** [comment]
You would need to have one node with sufficient memory, as the process runs on one server only. So yes, 128 GB on one node is not enough.

**Comment by skgs1970** [comment]
Thanks Dr. Menzel for the clarifications. I have used the [kaiju_db_nr_euk_2021-02-24.tgz] and its working fine. Can you tell how much is the recommended RAM requirements.
Thanks again.

**Comment by skgs1970** [comment]
Thank you, Dr. Menzel

**Comment by DaRinker** [comment]
FWIW, the documentation's "recommended" memory requirements may need to be updated. Just installed the NR database and the documentation suggests 148GB RAM for this database. However, that did not prove to be enough RAM and the process was killed after it hit 151GB (and since no output had been written yet, I assume the minimum requirement is in excess of 151GB...)

**Comment by pmenzel** [comment]
@DaRinker the numbers in the table were measured in April 2022 (see footnote). The actual memory usage probably varies a bit depending on the actual system where the program is run. 

Also, when making the index now in October, the database will be bigger and more memory is required.
