### ISSUE TITLE
Tips on running kaiju most efficiently on a shared cluster?

### ISSUE THREAD

**Issue by DaRinker** [bioinformatics-centre/kaiju#244]
The below is only an "ISSUE" with respect to the limited, existing information I've been able to locate on the topic. In particular, I did not uncover much with respect to kaiju-multi or multithreading behavior.
++++
Hello. I am new to kaiju but already have questions about how kaiju runs and how I should configure my pipeline for most efficient execution. 

BACKGROUND: I have >50 large fastq (40 million reads each) that I want to scan using the nr database. I have built the DB and have been experimenting with a single, small fastq (5,000 reads) to estimate runtime, memory requirements, etc.

OBSERVATION: Even with the small read file and 256GB of RAM, output does not begin to emerge until after an hour of run time. I assume this delay is related to the time it takes to load the DB into memory (?)

MOTIVATION: I would like to maximize this use of my computational resources (i.e. getting 256GB RAM on a single node on a shared cluster can sometimes be challenging). My original plan was to submit each of my fastq files as a separate job (each with a 256GB footprint) but given the load time, I am now wondering if there isn't a better way?

QUESTIONS:

- Should I be using kaiju-multi instead of kaiju? Is the idea behind kaiju-multi that it loads everything into RAM just once and then churns through each of the fastq files in succession?

- Does multi threading "see" (or care about) the number of processors/cores on a node? I'm currently only asking SLURM to reserve 256GB (--mem=256G) to maximize my chances of getting a node--however, the downside is I have no idea how many cores that will equate to on whichever node I land. Will kaiju run more efficiently if I start requesting specific numbers of cores that are in proportion the the number of threads I request? 

Thank you

**Comment by pmenzel** [comment]
Yes, running multiple fastqs with only loading the index to memory once is the use case of kaiju-multi.

When you submit the job to a queuing system, make sure that you also request the proper number of CPUs / cores / processors (the terminology might vary depending on the queueing system), when you want to run kaiju with multiple threads using option `-z`.

**Comment by DaRinker** [comment]
Thank you for the clarifications. Very instructive. I will now start requesting specific numbers of processors and begin using kaiju-multi to make more efficient.
