### ISSUE TITLE
Problem with kaiju-multi mode 

### ISSUE THREAD

**Issue by ElsaMMendes** [bioinformatics-centre/kaiju#247]
Impossible to run kaiju-multi in MEM mode.
At first it says: Error: E-value calculation is only available in Greedy mode. Use option: -a greedy

**Comment by pmenzel** [comment]
Do you use any additional command line options besides `-a mem` when running kaiju-multi?
Also, which version do you use?

**Comment by ElsaMMendes** [comment]
I use these line options: -z  -t  -f  -i  -j and   -v

**Comment by ElsaMMendes** [comment]
The version I work with is the one updated by a national cluster I'm using: 
https://gitlab.com/ifb-elixirfr/cluster/tools/-/merge_requests/952

**Comment by pmenzel** [comment]
Thanks, I made a release for kaiju 1.9.1.
It will probably be automatically in bioconda in a day or two.

**Comment by ElsaMMendes** [comment]
Thanks 
So with this new version, it should work on the cluster ? I'll try as soon as the new version is available and installed and tell you if I have still a problem.

**Comment by pmenzel** [comment]
Great, kaiju 1.9.2 is already in bioconda.

**Comment by ElsaMMendes** [comment]
Thanks now it works !!!!!!
