### ISSUE TITLE
Why is the percent unclassified (including "cannot be assigned to <taxa-level>") lower for species than for genus?

### ISSUE THREAD

**Issue by LLansing** [bioinformatics-centre/kaiju#249]
I ran Kaiju with the nr_euk database and produced summary tables for each taxa rank (phylum, class, order, family, genus, species).

I'm interested in the % of reads that were classified at each taxa rank; I expected that at a lower taxa level, fewer and fewer reads would be classified. I sum the "unclassified" and "cannot be assigned to a (non-viral) <taxa-level>" together to represent all unclassified reads for the given taxa level.

I found that the trend I had expected is mostly right, except species has a smaller % unclassified than all other taxa levels but phylum. The following is the order from smallest %unclassified to highest:

> phylum, species, class, order, family, genus

My intuition is that a sequence read classified at the taxa level must have been classified at all taxa levels above (genus, family, etc.), but my results don't reflect this. **What am I missing here?**

**Comment by pmenzel** [comment]
Hm hard to tell without seeing the results..

It could be caused by species that are "unclassified" and have no intermediate ranks.
E.g. all the taxa in [this list ]( https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=84086&lvl=3&lin=f&keep=1&srchmode=1&unlock) have the rank species with the next highest rank being phylum (Firmicutes). Those taxa exist for all phyla, but also intermediate ranks.

**Comment by LLansing** [comment]
Thanks for the response.
Perhaps there is an abundance of these taxa without intermediate ranks in my sequences. If such taxa are the cause of my results, I'm surprised to see how abundant they are. The results show ~75% reads are unclassified/unassignable for the genus level, but this drops to ~50% for the species level

**Comment by pmenzel** [comment]
Well, you could check if that it really the cause, do you see some of such species in the species-level report? There are often also species assigned to other intermediary taxa with names as _incertae sedis_ or _Candidatus_

**Comment by LLansing** [comment]
In fact, there are a 3409 of _Candidatus_ species classified across 719 samples.
I had suspected these taxa, although I checked the NCBI taxonomy of some of them and saw that they seemed to have intermediate taxa classifications (e.g. [Candidatus Solibacter usitatus](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=332163&lvl=3&lin=f&keep=1&srchmode=1&unlock)). 
I suppose a (potentially large) subset of _Candidatus_ taxa do not have intermediate ranks.
