### ISSUE TITLE
Missing argument -p for kaijuReport

### ISSUE THREAD

**Issue by rasmusagren** [bioinformatics-centre/kaiju#25]
kaijuReport doesn't take -p as an argument for printing full taxon paths.

**Comment by pmenzel** [comment]
Do you have the latest version from GitHub? That option was introduced in https://github.com/bioinformatics-centre/kaiju/commit/3b09ea49caf3484b9ae4a0e61474c37ec802e045

**Comment by rasmusagren** [comment]
Well, at least I _thought_ I had the latest version :) Turns out that I was using the latest release (1.4.4) instead. Maybe it would be good to make a new release though, since the -p flag is mentioned in the manual? I speak in self interest since what I'm doing requires a tarball.

**Comment by pmenzel** [comment]
Probably you are right, in that it's time to make a new release, then all the latest commits are bundled..

btw, [this tarball](https://github.com/bioinformatics-centre/kaiju/archive/master.tar.gz) should always have the latest version from GitHub.

**Comment by rasmusagren** [comment]
Great! I didn't know that there was a master tarball functionality. Good to know, but it wouldn't have helped me now since I'd need the md5 checksum to be fixed.

**Comment by pmenzel** [comment]
I made a new release for 1.4.5, you can also download a [tarball](https://github.com/bioinformatics-centre/kaiju/archive/v1.4.5.tar.gz) for that particular version, which will not change. There is also a  [tarball](https://github.com/bioinformatics-centre/kaiju/releases/download/v1.4.5/kaiju-1.4.5-linux-x86_64.tar.gz) for statically linked binaries for Linux.
