### ISSUE TITLE
Creating classification summary and merging multiple output

### ISSUE THREAD

**Issue by apoosakkannu** [bioinformatics-centre/kaiju#250]
Hi, I wonder could it be possible to have full taxonomy information instead of just specific level (example - just species) in creating classification summary step. Please let me know if it is possible somehow?

Also i wonder could it be possible to merge multiple output to have abundance table for all the samples in a single file?

Thanks in advance!

**Comment by pmenzel** [comment]
Hi,
1. no, one needs to give the rank to kaiju2table
2. you can give multiple kaiju output files to kaiju2table and it will make one big report with one column for each file, see https://github.com/bioinformatics-centre/kaiju#creating-classification-summary
