### ISSUE TITLE
Processing of non-canonical amino acids

### ISSUE THREAD

**Issue by alvanuffelen** [bioinformatics-centre/kaiju#251]
in the ```kaiju-makedb``` file, the creation of an the nr database is defined as:
```kaiju-mkbwt -e $exponentSA_NR -n $threadsBWT -a ACDEFGHIKLMNPQRSTVWY -o $DB/kaiju_db_$DB $DB/kaiju_db_$DB.faa```
However, the NCBI NR database contains [non-canonical amino acids](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp) such as B, U, Z and X. 
In the ```mkbwt``` file it states:

>  Characters not in the alphabet are set to the last char - so if you want to
  include a wildcard, the alphabet should have e.g. X as the last charater.
  For proteins the alphabet might look like this
       ACDEFGHIKLMNPQRSTVWYX

Following that logic, are the non-canonical amino acids converted to the wildcard Y in your command?

Additionally, I want to add the non-canonical amino acids to the database by extending the alphabet.
But then how are the blosum scores calculated if a canonical amino acid from the input is mismatched with a non-canonical amino acid from the database?

**Comment by pmenzel** [comment]
kaiju-makedb removes all non-canonical chars from the fasta files before calling mkbwt.
The conversion of RefSeq gbk files additionally converts B to D and Z to E.

It's rather easy to change the mkbwt call, but the kaiju c++ code itself is not really flexible regarding extending the alphabet and changing that and also changing the hard-coded blosum62 matrix would be rather involved..

**Comment by alvanuffelen** [comment]
Thanks for the clarification!
So you suggest to remove all sequences with non-canonical amino acids from my database? 

Hypothetically, I can extend the alphabet and build the database with non-canonical amino acids. But then what will happen if an amino acid from my input is paired with a non-canonical amino acid from my database?
I would assume in mem-mode, it would just count as mismatch. But how does greedy-mode handles this?

**Comment by pmenzel** [comment]
1. You could also just remove the individual characters from the sequences, e.g. by `perl -lpe 'y/BZ/DE/; s/[^ARNDCQEGHILKMFPSTWYV]//gi'`

2. That's a good question, I think there is a BLOSUM62 matrix with additionals entries..
