### ISSUE TITLE
Merge Fungi (Refseq) with Refseq (Bacteria and archaea) 

### ISSUE THREAD

**Issue by ShrutiKetan** [bioinformatics-centre/kaiju#254]
Thanks for the amazing tool!  I was wondering if there is a way to merge fungi and refseq db?
I want to compare the results between the two databases.
 Is there something I should watch out for while comparing these database?

**Comment by pmenzel** [comment]
Hi, what exactly do you mean? merge the fasta files of both databases before making the kaiju index? that should be straightforward.

**Comment by ShrutiKetan** [comment]
Sorry if I am unclear.
I have two databases:
kaiju-makedb -s refseq
kaiju-makedb -s fungi 
Generating two nodes.dmp, names.dmp, merged.dmp. Can I combine these two to make refseq+fungi.dmp?

**Comment by pmenzel** [comment]
when you made the databases at the same time (more or less) you can just use one of the sets of dmp files, they should not be different..

**Comment by ShrutiKetan** [comment]
Oh!! That is an oversight from my side. 
Thank you for your time
