### ISSUE TITLE
Reads classification algorithm

### ISSUE THREAD

**Issue by adieg** [bioinformatics-centre/kaiju#259]
Hi!

I'm running Kaiju and have a question regarding the classification in the .out file.
I'd be grateful if you could explain the classification algorithm in cases such as the follows:
```
C	A00929:735:HHL33DRX2:1:1101:24650:1000	2	111	2,191303,	EFF63980.1,WP_039930952.1,	YGKRVKYSKKYAAHDELNEAQ,
```
In this case, the potential hits are either bacteria (2) or Turicibacter (191303). How can it be that these are the only potential hits and why is the decision made to classify the read to (2)? I would assume that there were several species with the same score so why do I see only the high rank taxons and not the species level in this case?

Thanks,
Adi

**Comment by pmenzel** [comment]
Hi!

in this case, kaiju found two matches with score `111` for the sequence `YGKRVKYSKKYAAHDELNEAQ` (I guess it was the nr database), which have accession numbers [EFF63980.1](https://www.ncbi.nlm.nih.gov/protein/EFF63980.1) and [WP_039930952.1](https://www.ncbi.nlm.nih.gov/protein/WP_039930952.1). These accessions have taxon IDs `191303` and `2`. 
**Kaiju will always assign the taxon ID of the least common ancestor of all equally good matches as the final output taxon**, which is `2` in this case.

If you look at the Identical Protein Groups page for [WP_039930952.1](https://www.ncbi.nlm.nih.gov/ipg/WP_039930952.1), you see that there are many entries in Genbank with identical sequence. Most of them are [Turicibacter sanguinis](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=154288), but there are also two entries of [Bacteroides xylanisolvens](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=371601).
As both species belong to different phyla, the record WP_039930952.1 is assigned to Bacteria, which is the LCA of both.

Now one could argue that the few Bacteroides xylanisolvens entries are wrongly annotated in GenBank, but that is a different topic :)

**Comment by adieg** [comment]
Ok, now I get it :)
Thanks for the quick and elaborated answer!
