### ISSUE TITLE
kaiju-makedb -s viruses _ Missing file

### ISSUE THREAD

**Issue by Viola-TA** [bioinformatics-centre/kaiju#261]
Hello all,
I tried to create the virus database with the following command:

**kaiju-makedb -s viruses**

But it shows me an error that I did not find among the errors already reported:

kaiju-makedb -s viruses

Downloading taxdump.tar.gz
taxdump.tar.gz                 100%[==================================================>]  58,54M  10,2MB/s    in 6,2s    
2023-05-03 13:44:12 URL:http://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz [61378716/61378716] -> "taxdump.tar.gz" [1]
Extracting taxdump.tar.gz
Downloading virus genomes from RefSeq
**Missing file viruses/source/viral.*.genomic.gbff.gz**

Can someone help me what happened?

Thanks a lot

**Comment by pmenzel** [comment]
I just tried the command and didn't get the error.

Do you use the latest version of kaiju?
There have been some changes regarding downloading files from RefSeq in the last versions..

**Comment by Viola-TA** [comment]
Yes, I have the latest version of Kaiju.
But I think I have now also found the error. 

I had tried to create the database on a different hard drive than the one on which Kaiju is stored. 
I have now repeated the command on the same hard drive and it worked, all files are there. 
I think this was the error and the required files could not be found.

But many thanks for the quick feedback.
