### ISSUE TITLE
building refseq database readFasta: No sequences read

### ISSUE THREAD

**Issue by pratibha-kadam** [bioinformatics-centre/kaiju#268]
Hello There,

I am trying to install the refseq database in my computer but the sequences
![Screenshot from 2023-08-01 15-25-16](https://github.com/bioinformatics-centre/kaiju/assets/88572259/09116a94-7092-4d58-a191-f482c8fc9b1d)
 are not written in .faa file of kaiju_db_refseq file.

Please let me know whether this the expected output or is there something wrong.

**Comment by pmenzel** [comment]
Hi,

were any genomes downloaded at all? See the refseq/source folder.
Anyways, you can download a recent pre-built index from here: https://bioinformatics-centre.github.io/kaiju/downloads.html

**Comment by pratibha-kadam** [comment]
Hello, @pmenzel

Thanks for the response.

I have .gbff.gz files and .gbff.gz.faa(empty)  files in source folder.

**Comment by pmenzel** [comment]
then maybe it's related to the warning you got by xargs there.

**Comment by pratibha-kadam** [comment]
okay. Thanks a lot for the support and quick reply.
Really appreciate that.
