### ISSUE TITLE
Kaiju run command gets killed

### ISSUE THREAD

**Issue by pratibha-kadam** [bioinformatics-centre/kaiju#269]
I am running kaiju command

kaiju  -t kaiju_refseq_db/nodes.dmp -f kaiju_refseq_db/kaiju_db_refseq.fmi -i /media/fmr/HDD2/Metagenomics_31-07-2023/demo-data_R1.fastq -j /media/fmr/HDD2/Metagenomics_31-07-2023/demo-data_R2.fastq -o kaiju-output -z 15

it gets killed 

I tryied multiple times and reduced the threads to 8 but still getting the same error.

Please let me know the solution for this.

Device details:
RAM: 64GB
Processor:16 threads

**Comment by pratibha-kadam** [comment]
An update for the issue:

I have tried to run the process on each thread number (ex 1-8) it is not working even without threads and got killed.
I have even tried to change the hard drive to work still it is not working. I have 300GB empty space in my drive.

Please help me.

**Comment by pmenzel** [comment]
see the table in the README file for memory requirements of each reference database

**Comment by pratibha-kadam** [comment]
Thanks
