### ISSUE TITLE
error:Taxon ID in output file is not contained in taxonomic tree file nodes.dmp

### ISSUE THREAD

**Issue by ataravarice** [bioinformatics-centre/kaiju#27]
Hi
After running kaiju to annotate a marine virus database,I tried to use kt2krona file to illustrate the result.The programs shows many "Taxon ID  xx in output file is not contained in taxonomic tree file nodes.dmp" on the screen and the sequences are mostly annotated as influenza virus. The nodes.dmp is already newest(105.7MB).

the error is like this:
Warning: Taxon ID 7006495 in output file is not contained in taxonomic tree file nodes.dmp.
Warning: Taxon ID 7517995 in output file is not contained in taxonomic tree file nodes.dmp.

and I can find the ID No. in the .out file like:
C	gene_24783|GeneMark.hmm|115_aa|-|336|683	7006495

So is this taxon ID in the names.dmp file or in the .fmi file?

**Comment by pmenzel** [comment]
Hi,

how did you make your kaiju database? 

Kaiju uses the nodes.dmp and names.dmp files from NCBI to get the structure of the taxonomic tree (nodes.dmp) and map taxon ids to the actual names of the taxa (names.dmp).
This means that when you make a database, that the taxon ids in your database need to be contained in these files.

You can also cross-check at the [NCBI taxonomy website](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi). For example, when searching for 7006495, then no entry is found there.

**Comment by ataravarice** [comment]
I use NCBI non-redundant viral proteins to make a customed database.
![default](https://cloud.githubusercontent.com/assets/25415762/22421349/a0f86222-e721-11e6-94ea-7cb585563b10.png)


I tried kaijup,it worked well,but the result is different from kaiju program.Kaijup program linked the input sequences to gi Numbers and can be found in NCBI taxonomy website. The taxon number is different from how kaiju annotated the same sequence.

I pick a single sequence to make a test,this sequence can be annotated by kaijup as i|712913802,taxon number 35343,while in kaiju the taxon number is 9100909,a taxon number cannot be found,and the numerical value is exactly the YP number.

So my mistake is the taxon id is not contained in the NCBI virus nr database,thus not in the .fmi database file.

Many thanks to your kind explanation.Can I use addTaxonNames program to add taxon numbers to the nr database fasta file?

**Comment by pmenzel** [comment]
When you want to make a custom database for kaiju, the fasta headers need to be in the format described  [here](https://github.com/bioinformatics-centre/kaiju#custom-database).

I would recommend that you just use the whole NR database and not only its viral subset. You can make one by `makeDB.sh -n` or just download the one from the [web server](http://kaiju.binf.ku.dk/database/kaiju_index_nr.tgz). 

`makeDB.sh` uses the program `convertNR` to transform the NR database to Kaiju's format. It needs the file `prot.accession2taxid` which you can extract from [here](ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz).

So, in principle you could run it by yourself. Say your viral NR subset is in file `nrviralproteins.faa`, then you could run:

```
convertNR -t nodes.dmp -g prot.accession2taxid -c -o kaiju_db.faa -i nrviralproteins.faa
mkbwt -n 5 -a ACDEFGHIKLMNPQRSTVWY -o kaiju_db kaiju_db.faa
mkfmi kaiju_db
```
Then you get `kaiju_db.fmi` for  running Kaiju.

**Comment by ataravarice** [comment]
Is prot.accession2taxid the ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.

Thanks, your help is exactly what I need.

**Comment by pmenzel** [comment]
Sorry, forgot to add the link. Yes it's this file, uncompressed:
ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz

**Comment by Tamtatatam** [comment]
Hi 

I have a similar problem. I have several files from the kaiju webserver and I would like to combine them using kaiju2table. 

However, I get dozens of warnings ("Warning: Taxon ID XY is not contained in nodes.dmp."). I tried using the latest nodes.dmp and names.dmp, and also downloaded older versions from NCBI as the webserver uses older databases, but that did not help. 

Is that a known and expected problem, or am I using the wrong files? If so, which version should I use? 

Thanks!
