### ISSUE TITLE
kaiju-makedb mar and mar_db

### ISSUE THREAD

**Issue by spencerlong1** [bioinformatics-centre/kaiju#270]
Hi,

I am having some issues with the kaiju-makedb command with mar and mardb (seems to be a near identical issue for both). The output from kaiju-makedb -s mar_db is as follows:

\033[0;32mDownloading taxdump.tar.gz\033[0m
.listing                                             [ <=>                                                                                                      ]   1.85K  --.-KB/s    in 0.009s  
2023-08-31 12:57:40 URL: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz [1890] -> ".listing" [1]
\033[0;32mExtracting taxdump.tar.gz\033[0m
\033[0;32mDownloading MarDB metadata from MMP (databasesapi.sfb.uit.no)\033[0m
\033[0;32mCurrent MarDB version is: 1.6\033[0m
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1349k    0 1349k    0     0  5091k      0 --:--:-- --:--:-- --:--:-- 5091k
\033[0;32mDownloading MarDB complete genomes from the Marine Metagenomics Portal using 5 threads\033[0m
mv: cannot stat 'mar_db/source/public.sfb.uit.no/MarDB/genomes/*': No such file or directory

this is similar for when i just use -s mar, except it is:

\033[0;32mDownloading MarRef reference genomes from the Marine Metagenomics Portal using 5 threads\033[0m
mv: cannot stat 'mar/source/public.sfb.uit.no/MarRef/genomes/*': No such file or directory

there is nothing within my mar or mar_db/source directories after these errors, and I assume there is an issue with the download?

Do you know any fixes or alternatively, anywhere I can download an already compiled mar database for kaiju?

**Comment by pmenzel** [comment]
Removed Mar databases again from kaiju as they are no longer supported.
