### ISSUE TITLE
Segmentation fault error in kaiju-mkbwt

### ISSUE THREAD

**Issue by LilyAnderssonLee** [bioinformatics-centre/kaiju#276]
I encountered an `Segmentation fault` error whiling constructing a custom database using compressed RefSeq data with the following command: `kaiju-mkbwt -n 36 -a protein -infilename ../ncbi/protein/complete.protein.faa.gz -o complete_protein`.

However the error disappeared when using decompressed `complete.protein.faa`.  I am wondering if the input data must be decompressed.

**Comment by pmenzel** [comment]
yes, mkbwt reads plain faa files, see the README.

**Comment by LilyAnderssonLee** [comment]
Thanks! I think I overlooked!
