### ISSUE TITLE
"Behind the Paper" Link Seems to be Broken

### ISSUE THREAD

**Issue by GilChrist19** [bioinformatics-centre/kaiju#284]
The link [here](https://github.com/bioinformatics-centre/kaiju/blob/7532375ad219cf675f6c75d2d7228b765964b997/index.html#L309C26-L309C180) seems to be gone. 

I think the corresponding article is this one: https://communities.springernature.com/posts/from-metagenomics-of-hot-springs-to-bioinformatics-software-development

**Comment by pmenzel** [comment]
thanks for reporting!
