### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kseniaarkhipova** [bioinformatics-centre/kaiju#29]
Hi!
I am trying to use kaiju as a quick aligner of sequences and I do not need taxonomic classification and, on the contrary, want to save original fasta headers in the database.  I built the database with mkbwt and mkfmi without changing headers in fasta file. When I launch kaijup, it is perfectly work for a while and stop with a "Segmentation fault (core dumped)". I am using nr and a big query file, but I am monitoring resources usage and there are plenty of them on my machine (near 300Gb of RAM is still available at the "core dump" point). But the most interesting point, that I relaunched it many times with the same everything and it crashed at different moments. So I am not sure that this is because of headers in the database. Do you have any idea what can cause this failure? 
At the same time, did not you consider to make a special mode for using kaiju just as "blast" alternative? It is madly fast and for many metagenomics tasks it would be very-very useful. If the output included lengths of both aligned sequences, original identifiers (fasta headers) and length of match, it would be much more universal.
Thank you for your work!
Ksenia

**Comment by pmenzel** [comment]
Hi Ksenia,

Hm, these segmentation faults are hard to debug, it could be that the headers might be too long, did you try to just keep the accession number in the fasta database file? The memory requirement should really not exceed 50GB or so for the NR database no matter how many threads. If you still have the core file, you could try to load it into gdb with `gdb /path/to/kaiju core`, followed by `thread apply all bt` to see the stacktrace of all threads.

Did you compile Kaiju on the same system where you are running it? Maybe it's also worth to try out the static builds from [here](https://github.com/bioinformatics-centre/kaiju/releases/download/v1.4.5/kaiju-1.4.5-linux-x86_64.tar.gz)

Regarding your second question, Kaiju is really not be meant as a replacement for traditional aligners like blast or mappers like bwa. Kaiju's focus really is a fast assignment of reads to the sequences in a reference database by using a heuristic search for maximum exact matches (with some allowed substitutions in greedy mode); it does not allow for gaps for example or keeps track of sub-optimal matches.  The length of the match and the matching sequences are reported by kaijup.

**Comment by kseniaarkhipova** [comment]
Peter, thank you for your very quick response!
I tried static build you provided link for, surprisingly it worked much longer (~3 times) but, finally, also crashed with the same core dump problem. Headers in my database are no longer that 40 characters, I suppose they are short enough. Unfortunately, I am not a programmer and did not understand anything about "core file", so do not know how to test this. 
Ksenia

**Comment by pmenzel** [comment]
Hm, then it's difficult for me to help.. maybe you can try to run the standard kaiju first with a standard NR taxonomy database by running `makeDB.sh -n`. If your input is already protein sequences, you can use option `-p` for kaiju. If that works, then it could really be a problem with your database file..

**Comment by okapick** [comment]
If you are working with a virtual machine. You can try to give more RAM. Because I give around 55 GB ram more 13GB swap. Then i could solved it.

Regards.
