### ISSUE TITLE
Kaiju NR

### ISSUE THREAD

**Issue by milkbugdoctor** [bioinformatics-centre/kaiju#3]
Is its possible to include all the Eukaryotic sequences in the kaiju  database as well when making the database from the NCBI NR  fasta file. Currently covertNR seems to get rid of anything that is not prokaryotic or viral. I expect certain metagenomes that I am analyzing to contain fungi and protists (based on Kraken results) , which I hope to classify using your wonderful tool.

**Comment by pmenzel** [comment]
The last commit had already support for fungi and microbial eukaryotes; it was just not announced on the website. Use option `-e` for `makeDB.sh`, which will include all proteins belonging to the taxa listed in the file `taxonlist.tsv`. I also recommend to use the option `-x` for filtering low complexity regions. 

The [webserver](http://kaiju.binf.ku.dk) now also includes a selection for the NR+euk database.
