### ISSUE TITLE
OS X ld does not support --whole-archive option

### ISSUE THREAD

**Issue by HadrienG** [bioinformatics-centre/kaiju#30]
Since 1.4.5, building kaiju from source fails on OSX.

```
gcc   mkbwt.o readFasta.o suffixArray.o multikeyqsort.o sequence.o  -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -lm -o mkbwt
ld: unknown option: --whole-archive
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I managed to build using `-all_load` and `-noall_load` instead of `--whole-archive` and `--no-whole-archive`, respectively, but this will not build on Linux.

I guess you could use something like

```
OS := $(shell uname)
ifeq $(OS) Darwin
LDLIBS = -Wl,-all_load -lpthread -Wl,-noall_load -lm 
else
LDLIBS = -Wl,--whole-archive -lpthread -Wl,--no-whole-archive -lm
endif
```

in both makefiles as a quick fix to the problem, or use [autoconf](https://www.gnu.org/software/autoconf/autoconf.html) to build portable binaries.

Hope this helps,
Hadrien.

PS: Thank you for your work, your software is awesome! 🎉 🐨 😃

**Comment by pmenzel** [comment]
Hi Hadrien,

thanks for the bug report! I don't have a Mac, so I don't see these problems normally.. :)

I put that the `--whole-archive` thing in there to make the static binaries work on some systems, but it is actually not needed for the normal dynamically linked binaries. So, I will move it out from there as a first fix. For fixing the static compilation on MacOS, that `if`-test seems good, but probably I should not test for Darwin, but for the compiler and see if it is clang or gcc.
Or use autoconf at some point in time..

PS: Glad that you like Kaiju! :+1:

**Comment by pmenzel** [comment]
I modified the makefile now to not use `--whole-archive` when doing a normal `make`. Would you please test that it works for you?

**Comment by HadrienG** [comment]
It works! 🎉

**Comment by lmoneta** [comment]
--while-archive does not work on MacOs. 
I think one should use -all_load in this case

**Comment by danem** [comment]
> --while-archive does not work on MacOs.
> I think one should use -all_load in this case

Beware, that this option will subtly break linking for other libraries. Use `-force_load` instead as it only applies to the single library.

**Comment by pmenzel** [comment]
@danem: So instead of `-Wl,-all_load -lpthread -lz -Wl,-noall_load` one would use `-Wl,-force_load -lpthread -lz -Wl,-noforce_load` ?
