### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by rosema62** [bioinformatics-centre/kaiju#32]
I get the following error when invoking make

[rosema1@demeter kaiju-master]$ cd src/
[rosema1@demeter src]$ make
make -C bwt/
make[1]: Entering directory `/home/rosema1/BioInfo/bin/kaiju-master/src/bwt'
gcc -O3 -g -Wno-unused-result   -c -o mkbwt.o mkbwt.c
gcc -O3 -g -Wno-unused-result   -c -o readFasta.o readFasta.c
gcc -O3 -g -Wno-unused-result   -c -o suffixArray.o suffixArray.c
gcc -O3 -g -Wno-unused-result   -c -o multikeyqsort.o multikeyqsort.c
gcc -O3 -g -Wno-unused-result   -c -o sequence.o sequence.c
gcc   mkbwt.o readFasta.o suffixArray.o multikeyqsort.o sequence.o  -lpthread -lm -o mkbwt
gcc -O3 -g -Wno-unused-result   -c -o mkfmi.o mkfmi.c
gcc -O3 -g -Wno-unused-result   -c -o bwt.o bwt.c
gcc -O3 -g -Wno-unused-result   -c -o compactfmi.o compactfmi.c
gcc   mkfmi.o bwt.o suffixArray.o compactfmi.o  -lpthread -lm -o mkfmi
make[1]: Leaving directory `/home/rosema1/BioInfo/bin/kaiju-master/src/bwt'
g++ -ansi -pedantic -O3 -pthread -std=c++11 -g -DNDEBUG -Wall -Wconversion -Wno-unused-function -I./include/ProducerConsumerQueue/src -I./include/ncbi-blast+ -c -o kaiju.o kaiju.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [kaiju.o] Error 1

Help would be appreciated.

Mark

**Comment by pmenzel** [comment]
That is because your compiler is too old and does not support the C++11 standard, which is supported from GCC 4.7 onwards. If you cannot update your compiler, then you could try to use the statically build binary files from [here](https://github.com/bioinformatics-centre/kaiju/releases/download/v1.5.0/kaiju-1.5.0-linux-x86_64.tar.gz).
