### ISSUE TITLE
Plasmids as a reference database

### ISSUE THREAD

**Issue by koopkaup** [bioinformatics-centre/kaiju#34]
Is it possible to add plasmids protein sequences from Refseq as a reference database?
ftp://ftp.ncbi.nih.gov/refseq/release/plasmid/

**Comment by pmenzel** [comment]
In principle it is possible, it's a similar format as the viral proteins from RefSeq.
How big is the overlap between the plasmids in these files and the plasmids that come together with the individual genome assemblies from RefSeq?

**Comment by koopkaup** [comment]
I have to check that, but my objective is to distinguish only plasmids from metagenomic reads. Right now it is not possible using kaiju results. 

And another feature request is to output classified sequences as a fasta file.

**Comment by pmenzel** [comment]
If you only want those plasmids in you kaiju database, you can just make your own without using makeDB.sh.  
First download the files:
```
wget ftp://ftp.ncbi.nih.gov/refseq/release/plasmid/plasmid.1.genomic.gbff.gz
wget ftp://ftp.ncbi.nih.gov/refseq/release/plasmid/plasmid.2.genomic.gbff.gz
wget ftp://ftp.ncbi.nih.gov/refseq/release/plasmid/plasmid.3.genomic.gbff.gz
```
Also download the NCBI taxonomy:
```
wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
tar xf taxdump.tar.gz nodes.dmp names.dmp
```
Then, extract the protein sequences and make the database, assuming that Kaiju is installed in `~/software/kaiju/`:
```
find . -name "plasmid.*.genomic.gbff.gz" | xargs -n 1 -P 3 -i ~/software/kaiju/bin/gbk2faa.pl '{}' '{}'.faa
cat plasmid*faa >kaiju_db.faa
~/software/kaiju/bin/mkbwt -n 3 -e 3 -a ACDEFGHIKLMNPQRSTVWY -o kaiju_db kaiju_db.faa 
~/software/kaiju/bin/mkfmi kaiju_db
```
Now you got the `kaiju_db.fmi` file and run Kaiju with, for example:
```
~/software/kaiju/bin/kaiju -x -a greedy -e 3  -t nodes.dmp -f kaiju_db.fmi -i reads.fastq -o kaiju_out.txt
```

**Comment by pmenzel** [comment]
Your other feature request will probably not be implemented soon.

But from Kaiju's output file you get the read names, which you can use to extract the reads from the original fastq file.

I tried this quick hack in Perl and it works on my one example data set, maybe it also works for you:
```
perl -lsane 'print $F[1] if $F[0] =~ /C/' kaiju.out >classifiedreadnames.txt
perl -lne 'BEGIN{open(F,"classifiedreadnames.txt");while(<F>){chomp;$h{$_}=1}}if($c++%4==0&&/^@/){@X=split(/[\s@]/,$_);if($h{$X[1]}==1){print;$p=1;}else{$p=0}}elsif($p){print;}' input_reads.fastq >classified_reads.fastq
```
No guarantee for that thing to work on all files though. ;)

**Comment by tseemann** [comment]
@koopkaup the main issue with NCBI taxonomy based databases is that plasmids are just bacteria. i would also like to be able to discriminate between them. it can be done with post-processing, or more complicated by creating a kingdom of fake taxonomy IDs for the plasmids (just an idea, never tried it!)
