### ISSUE TITLE
Found bad number (out of range error)

### ISSUE THREAD

**Issue by kengcher** [bioinformatics-centre/kaiju#35]
was trying kaiju out using the kaiju_index.tgz db and ran the command:
kaiju-v1.5.0-linux-x86_64-static/bin/kaiju -t *.dmp -f *.fmi -i firstfile.fq -j secondfile.fq -z 32

and received a whole bunch of warnings:
Found bad number (out of range error) in line: 1        |       all     |               |       synonym |
Found bad number (out of range error) in line: 1        |       root    |               |       scientific name |
Found bad number (out of range error) in line: 2        |       Bacteria        |       Bacteria <prokaryotes>  |       scientific name     |
Found bad number (out of range error) in line: 2        |       Monera  |       Monera <Bacteria>       |       in-part |
...

pls advise if this is expected?

Thank you.

**Comment by kengcher** [comment]
this was followed by: 
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted

**Comment by pmenzel** [comment]
Hi,
looks like you are passing the file `names.dmp` to the option `-t` by using the shell wildcard `*.dmp`.
Run it with:
``
kaiju -x -z 32 -t nodes.dmp -f kaiju_db.fmi -i firstfile.fq -j secondfile.fq -o kaiju.out
``

**Comment by kengcher** [comment]
thanks alot and indeed that was my error.
