### ISSUE TITLE
how to merge kaijuReport output files of multiple samples into one file?

### ISSUE THREAD

**Issue by lihongyi123** [bioinformatics-centre/kaiju#36]
Hi Peter
I have get 16 kaijuReport output files, and want to merge them together.
Does kaiju have any program for that? I suggest you to add this function into kaiju anyway.
Another question is that if kaiju takes genome size into account? Since large genome should have more reads sequenced comparing to small genome species.
By the way, thanks for such a good tool. I have tried kraken, but even less then 10%  of the metagenomic reads were classified, while kaiju gives me about 65%. with the greedy-5 mode and nr database

**Comment by pmenzel** [comment]
Hi Hongyi,
there is no built-in merging of the reports, but could be a feature in the future. Right now, I suggest you do that in R, should be quite simple.
Genome size is not easy to consider, because you only know the genome sizes of the individual strains in the database (e.g. when using RefSeq). Often reads are assigned to species or genus level, then you don't know which strain to use for normalization..
best,
Peter

**Comment by lihongyi123** [comment]
Hi Peter,
thanks for the reply.
I have get the merging result using R. But I found a misleading information from the "kaijuReport -h", which shows " -l            Print taxon path containing only ranks specified by a comma-separated list,
                 for example: superkingdom,phylum,order,class,family,genus,species".  The "order“ and ”class“  should be reversed or the result will be wrong when using the -l flag with out think the right order (like me).
best.
Hongyi

**Comment by pmenzel** [comment]
thanks! switched class and order now.

**Comment by m-ocejo** [comment]
Hi @lihongyi123 , could you please tell how to merge Kaiju results with R?

**Comment by lihongyi123** [comment]
Hi @m-ocejo, sorry for the delay. Try the code below:
#############################
setwd("/home/lhy/SOIL/Paddy_soil_silva_for_DOM/kaiju_out")
lista=list()
lista[[1]]=df_H02_s<-read.csv("kaiju_H02_s.out.summary",header=T,sep="\t")
lista[[2]]=df_H18_s<-read.csv("kaiju_H18_s.out.summary",header=T,sep="\t")
lista[[3]]=df_H22_s<-read.csv("kaiju_H22_s.out.summary",header=T,sep="\t")
lista[[4]]=df_H47_s<-read.csv("kaiju_H47_s.out.summary",header=T,sep="\t")

for (i in 1:4){
  #    a=which(lista[[i]][,3]=="") 
  #    lista[[i]]=lista[[i]][-a,]
  lista[[i]][,3]=as.character(lista[[i]][,3])
  lista[[i]][,1]=as.numeric(as.character(lista[[i]][,1]))
}
df_all_s=lista[[1]]
df_all_s[,1]=lista[[1]][,3]
df_all_s[,2]=lista[[1]][,1]
df_all_s[,3:5]=0
for (i in 1:3){
  L=length(lista[[i+1]][,1])
  for (j in 1:L){
    b=which(df_all_s[,1]==lista[[1+i]][j,3])
    if (length(b)){
      df_all_s[b,i+2]=lista[[1+i]][j,1]
    }else{
      LL=length(df_all_s[,1])
      df_all_s[LL+1,]=0
      df_all_s[LL+1,1]=lista[[1+i]][j,3]
      df_all_s[LL+1,i+2]=lista[[1+i]][j,1]      
    }
  }}
colnames(df_all_s)=c("taxon", "H02","H18","H22","H47")
write.table(df_all_s,file="kaiju_all_s.csv",sep="\t",col.names=T,row.names=F)
##################################
file “kaiju_H02_s.out.summary” looks like this：
        %	    reads	species
-------------------------------------------
 0.839180	   367046	Bacteria;Proteobacteria;Deltaproteobacteria;Myxococcales;Anaeromyxobacteraceae;Anaeromyxobacter;Anaeromyxobacter sp. Fw109-5;
 0.405794	   177489	Bacteria;Acidobacteria;Solibacteres;Solibacterales;Solibacteraceae;Candidatus Solibacter;Candidatus Solibacter usitatus;
 0.397955	   174060	Bacteria;Verrucomicrobia;Verrucomicrobiae;Verrucomicrobiales;Verrucomicrobia subdivision 3;Pedosphaera;Pedosphaera parvula;
 0.358091	   156624	Bacteria;Proteobacteria;Deltaproteobacteria;Myxococcales;Anaeromyxobacteraceae;Anaeromyxobacter;Anaeromyxobacter sp. RBG_16_69_14;
 0.308647	   134998	Bacteria;Proteobacteria;Deltaproteobacteria;Myxococcales;Polyangiaceae;Sorangium;Sorangium cellulosum;
 0.289261	   126519	Bacteria;Chloroflexi;NA;NA;NA;NA;Chloroflexi bacterium OLB14;
 0.270527	   118325	Bacteria;NA;NA;NA;NA;NA;uncultured bacterium;
 0.226001	    98850	Bacteria;Proteobacteria;Gammaproteobacteria;Nevskiales;Sinobacteraceae;Steroidobacter;Steroidobacter denitrificans;
···············································

**Comment by m-ocejo** [comment]
Hi @lihongyi123 ,
thank  you very much for your reply!
However, my kaiju reports are different. I have one file per sample and per taxonomic rank like this:
At phylum level:
```
        %	    reads	phylum
-------------------------------------------
65.155235	  9396803	Firmicutes
 2.161699	   311764	Proteobacteria
```
At family level:
```
        %	    reads	family
-------------------------------------------
10.238718	  1476646	Lachnospiraceae
10.079963	  1453750	Clostridiaceae
```

How did you get the Kaiju output with all the taxonomic levels like yours?
Thank you!

**Comment by lihongyi123** [comment]
Hi @m-ocejo ：
You have to combine files of one taxonomic rank first， then do the next rank.
what I have showed you is the code for one rank. The below code is what I used to combine samples at phylum and class levels. 
I use it for more than three samples. 
########################
setwd("/home/lhy/SOIL/Paddy_soil_silva_for_DOM/kaiju_out")
lista=list()
lista[[1]]=df_H02_p<-read.csv("kaiju_H02_p.out.summary",header=T,sep="\t")
lista[[2]]=df_H18_p<-read.csv("kaiju_H18_p.out.summary",header=T,sep="\t")
lista[[3]]=df_H22_p<-read.csv("kaiju_H22_p.out.summary",header=T,sep="\t")
lista[[4]]=df_H47_p<-read.csv("kaiju_H47_p.out.summary",header=T,sep="\t")
lista[[5]]=df_L01_p<-read.csv("kaiju_L01_p.out.summary",header=T,sep="\t")
lista[[6]]=df_L07_p<-read.csv("kaiju_L07_p.out.summary",header=T,sep="\t")
lista[[7]]=df_L20_p<-read.csv("kaiju_L20_p.out.summary",header=T,sep="\t")
lista[[8]]=df_L28_p<-read.csv("kaiju_L28_p.out.summary",header=T,sep="\t")
lista[[9]]=df_T09_p<-read.csv("kaiju_T09_p.out.summary",header=T,sep="\t")
lista[[10]]=df_T17_p<-read.csv("kaiju_T17_p.out.summary",header=T,sep="\t")
lista[[11]]=df_T31_p<-read.csv("kaiju_T31_p.out.summary",header=T,sep="\t")
lista[[12]]=df_T48_p<-read.csv("kaiju_T48_p.out.summary",header=T,sep="\t")
lista[[13]]=df_Y04_p<-read.csv("kaiju_Y04_p.out.summary",header=T,sep="\t")
lista[[14]]=df_Y24_p<-read.csv("kaiju_Y24_p.out.summary",header=T,sep="\t")
lista[[15]]=df_Y30_p<-read.csv("kaiju_Y30_p.out.summary",header=T,sep="\t")
lista[[16]]=f_Y43_p<-read.csv("kaiju_Y43_p.out.summary",header=T,sep="\t")   ###16 is the number you need to change, i.e. N

for (i in 1:16){         ###16 is the number you need to change, i.e. N
###   a=which(lista[[i]][,3]=="") 
####    lista[[i]]=lista[[i]][-a,]
    lista[[i]][,3]=as.character(lista[[i]][,3])
    lista[[i]][,1]=as.numeric(as.character(lista[[i]][,1]))
}
df_all_p=lista[[1]]
df_all_p[,1]=lista[[1]][,3]
df_all_p[,2]=lista[[1]][,1]
df_all_p[,3:17]=0                       ###17 is the number you need to change, i.e N+1
for (i in 1:15){                                ###15 is the number you need to change, i.e N-1
  L=length(lista[[i+1]][,1])
  for (j in 1:L){
    b=which(df_all_p[,1]==lista[[1+i]][j,3])
    if (length(b)){
df_all_p[b,i+2]=lista[[1+i]][j,1]
    }else{
      LL=length(df_all_p[,1])
df_all_p[LL+1,]=0
df_all_p[LL+1,1]=lista[[1+i]][j,3]
df_all_p[LL+1,i+2]=lista[[1+i]][j,1]      
    }
  }}
colnames(df_all_p)=c("taxon", "H02","H18","H22","H47","L01","L07","L20","L28","T09","T17","T31","T48","Y04","Y24","Y30","Y43")
write.table(df_all_p,file="kaiju_all_p.csv",sep="\t",col.names=T,row.names=F)
###############
#################################################################################################
setwd("/home/lhy/SOIL/Paddy_soil_silva_for_DOM/kaiju_out")
lista=list()
lista[[1]]=df_H02_c<-read.csv("kaiju_H02_c.out.summary",header=T,sep="\t")
lista[[2]]=df_H18_c<-read.csv("kaiju_H18_c.out.summary",header=T,sep="\t")
lista[[3]]=df_H22_c<-read.csv("kaiju_H22_c.out.summary",header=T,sep="\t")
lista[[4]]=df_H47_c<-read.csv("kaiju_H47_c.out.summary",header=T,sep="\t")
lista[[5]]=df_L01_c<-read.csv("kaiju_L01_c.out.summary",header=T,sep="\t")
lista[[6]]=df_L07_c<-read.csv("kaiju_L07_c.out.summary",header=T,sep="\t")
lista[[7]]=df_L20_c<-read.csv("kaiju_L20_c.out.summary",header=T,sep="\t")
lista[[8]]=df_L28_c<-read.csv("kaiju_L28_c.out.summary",header=T,sep="\t")
lista[[9]]=df_T09_c<-read.csv("kaiju_T09_c.out.summary",header=T,sep="\t")
lista[[10]]=df_T17_c<-read.csv("kaiju_T17_c.out.summary",header=T,sep="\t")
lista[[11]]=df_T31_c<-read.csv("kaiju_T31_c.out.summary",header=T,sep="\t")
lista[[12]]=df_T48_c<-read.csv("kaiju_T48_c.out.summary",header=T,sep="\t")
lista[[13]]=df_Y04_c<-read.csv("kaiju_Y04_c.out.summary",header=T,sep="\t")
lista[[14]]=df_Y24_c<-read.csv("kaiju_Y24_c.out.summary",header=T,sep="\t")
lista[[15]]=df_Y30_c<-read.csv("kaiju_Y30_c.out.summary",header=T,sep="\t")
lista[[16]]=f_Y43_c<-read.csv("kaiju_Y43_c.out.summary",header=T,sep="\t")

for (i in 1:16){
  ###   a=which(lista[[i]][,3]=="") 
  ###   lista[[i]]=lista[[i]][-a,]
  lista[[i]][,3]=as.character(lista[[i]][,3])
  lista[[i]][,1]=as.numeric(as.character(lista[[i]][,1]))
}
df_all_c=lista[[1]]
df_all_c[,1]=lista[[1]][,3]
df_all_c[,2]=lista[[1]][,1]
df_all_c[,3:17]=0
for (i in 1:15){
  L=length(lista[[i+1]][,1])
  for (j in 1:L){
    b=which(df_all_c[,1]==lista[[1+i]][j,3])
    if (length(b)){
      df_all_c[b,i+2]=lista[[1+i]][j,1]
    }else{
      LL=length(df_all_c[,1])
      df_all_c[LL+1,]=0
      df_all_c[LL+1,1]=lista[[1+i]][j,3]
      df_all_c[LL+1,i+2]=lista[[1+i]][j,1]      
    }
  }}
colnames(df_all_c)=c("taxon", "H02","H18","H22","H47","L01","L07","L20","L28","T09","T17","T31","T48","Y04","Y24","Y30","Y43")
write.table(df_all_c,file="kaiju_all_c.csv",sep="\t",col.names=T,row.names=F)
#####################
Best!
Hongyi

**Comment by pmenzel** [comment]
The new program `kaiju2table` can read multiple input files and outputs one table in long format with a combined report, which can then be easily imported e.g. to R.

**Comment by archiesachdeva** [comment]
Hi, I am trying to merge " .out " files from multiple samples using kaiju2table. However, I get an empty .tsv file when I use the following code

kaiju2table -t kaiju_db_nr/nodes.dmp -n kaiju_db_nr/names.dmp -r species -c 10 -o merge_3_samples.tsv Sample1.out, Sample2.out, Sample3.out -l superkingdom,phylum,class,order,family,genus,species

Is there something wrong with the way I write this statement?
Sample1.out, Sample2.out, Sample3.out are my output files from the classification step.

**Comment by pmenzel** [comment]
Try without the commas after Sample1.out and Sample2.out?

**Comment by archiesachdeva** [comment]
It works without commas. Thank you!

**Comment by Eljuanabee** [comment]
Hi, how did you import merge_3_samples.tsv into phyloseq?

**Comment by Eljuanabee** [comment]
Hi, someone knows how to import data from kaiju to phyloseq? 
How can I import the merge_3_samples.tsv file will the kaiju results into phyloseq? there is a way to produce the three tables (OTU, Samples, and Taxonomy) required for phyloseq from the merge results from kaiju? 
Thanks

**Comment by magibc** [comment]
Dear @archiesachdeva @pmenzel , 

Performing the following code for 156 kaiju.out files:

```
kaiju2table \
-t ${db}/nodes.dmp \
-n ${db}/names.dmp \
-r species \
-o ./prova_2_merge/Merged_species_files.tsv *.kaiju.out \
-l superkingdom,phylum,class,order,family,genus,species
```

I obtained an output to process to phyloseq. 

However in the logs file of the bash script appears for some times the same type of error (see below). 

```
Loading prerequisites.
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Loaded.
Loading prerequisites.
Loaded.
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Error: Found bad taxon id (out of range error) in line: C     A00500:65:H3CH3DRXX:1:210
Error: Found bad taxon id (out of range error) in line: C       A0050028
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Error: Found bad taxon id (out of range error) in line: C   A00500:65:H3CH3DRXX:1:210
Error: Found bad taxon id (out of range error) in line: C       A0050028
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Loading prerequisites.
Loaded.
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Loading prerequisites.
Loaded.
Error: Found bad taxon id (out of range error) in line: C       A00500:65:H3CH3DRXX:1:210
Error: Found bad taxon id (out of range error) in line: C       A0050028
Error: Found bad taxon id (out of range error) in line: C       A00500:65:H3CH3DRXX:1:210
Error: Found bad taxon id (out of range error) in line: C       A0050028

Error: Found bad taxon id (out of range error) in line: C A00500:65:H3CH3DRXX:1:210
```

Could help me to know his meaning in order to try to solve it.

Thanks on advance.
