### ISSUE TITLE
Doc on best match

### ISSUE THREAD

**Issue by davidvilanova** [bioinformatics-centre/kaiju#38]
Hi,
In the kaiju help explaining kaiju output it says:

4- the length or score of the best match used for classification.

Does this correspond to the total length of the best target of only the length of the aligned part of the target ? It´s not clear for me if you are representing the length. If it is score which score ?

Thanks for clarification,

**Comment by pmenzel** [comment]
In MEM mode, column 4 contains the length of the longest alignment between read and the database sequence (with lower bound controlled by option `-m`)

In Greedy mode, column 4 contains the Blosum62 score of the alignment with highest score (with lower bound controlled by option `-s`)

**Comment by davidvilanova** [comment]
Thanks for the update.
