### ISSUE TITLE
Make a custom database failed

### ISSUE THREAD

**Issue by xuuuuuuuuya** [bioinformatics-centre/kaiju#39]
I was tried to make a custom database based on arthropoda proteins. I created a the database fasta file named kaiju_test and ran in the kaiju/bin file:

mkbwt -n 5 -a ACDEFGHIKLMNPQRSTVWY -o proteins kaiju_test

and this is what I got:

-bash: kaiju: command not found

The file mkbwt is in the kaiju/bin directory. What could be the problem? Thanks for your time!

**Comment by pmenzel** [comment]
This error looks like you tried to run kaiju and not mkbwt. What exactly did you do? best is to copy everything from your terminal..
