### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by gazalk** [bioinformatics-centre/kaiju#42]
Hi, I'm trying to compile the program, but I'm facing this error because the header file which is included in  file hspfilter_collector.c is not available:
`error: No rule to make target '/algo/blast/core/blast_hits_priv.h', needed by 'obj/hspfilter_collector.o'.`

-Gazal

**Comment by pmenzel** [comment]
Hi,
I forgot to include that file (and maybe others too). Which compiler/version do you use?
You can try to download the file [here](https://www.dropbox.com/s/38e1wc2hnyon5g9/blast_hits_priv.h?dl=0) and put it into the directory `src/include/ncbi-blast+/algo/blast/core` of your kaiju installation and run `make` again..

**Comment by gazalk** [comment]
Thank you!!
Yes, I see your makefile, hspfilter_collector.c is not compiling (you have included extra files). I was trying to compile it using Qt Creator because I want to do some testing on the code, I changed the makefile locally. It compiles perfectly fine now - with compiler g++ 5.4(c++11) on Ubuntu.
