### ISSUE TITLE
Summary file

### ISSUE THREAD

**Issue by davidvilanova** [bioinformatics-centre/kaiju#43]
Hi ,
I have noticed that summary file are different if your input is a dna seq or a protein.
In the case of the proteins my output looks like this:

```
C       k141_11175_1    1282    Firmicutes; Bacilli; Bacillales; Staphylococcaceae; Staphylococcus; Staphylococcus epidermidis; 
C       k141_6414_1     31957   Actinobacteria; Actinobacteria; Propionibacteriales; Propionibacteriaceae; NA; NA; 
```

If input is DNA

```
C	k141_336_2	1574624	511	1574624,	WP_002548245.1,WP_063811380.1,	MNTLHSGILVVDKPAGVTSHQVVGRVRRLMGTRKVGHAGTLDPMANGVLIVGINRATRLLGHLSLHDKDYTATMRLGVGTVTDDAEGEVTATTDASAIDDE,	Actinobacteria; Actinobacteria; Propionibacteriales; Propionibacteriaceae; Cutibacterium; [Propionibacterium] namnetense; 

```

Why such difference ? Not talking about the taxonomy itself (it is just a random example) but rather a difference in the output format.

**Comment by pmenzel** [comment]
Hi, 

you run kaiju and then addTaxonNames afterwards, right?

Seems like in the second case you used option -v for verbose output when running kaiju, which will add [additional columns ](https://github.com/bioinformatics-centre/kaiju#output-format).

**Comment by davidvilanova** [comment]
Ooops,
Ok thanks !!!
