### ISSUE TITLE
verbose (-v) output "accession number" not shown

### ISSUE THREAD

**Issue by dovivi** [bioinformatics-centre/kaiju#44]
I've set to verbose output mode because I want to know the accession number of the sequence with best match, however the 6th column (the accession numbers of all database sequences with the best match) is empty in my output, but all other fields match to your description of the verbose output. See example of the output I get:

U	readname1	0
U	readname2	0
C	readname3	5125	18	5113,	PEYNILKNAYSLLGFKHS,
C	readname4	930090	33	930090,	ENPLKSRHDICFNYKNFRGCYLWTSKTTGKQYI,
C	readname5	930090	33	930090,	ENPLKSRHDICFNYKNFRGCYLWTSKTTGKQYI,

Your description:
1    either C or U, indicating whether the read is classified or unclassified.
2    name of the read
3    NCBI taxon identifier of the assigned taxon
4    the length or score of the best match used for classification
5    the taxon identifiers of all database sequences with the best match
**6    the accession numbers of all database sequences with the best match**
7    matching fragment sequence(s)

As you can see there is no column matching description number 6

Thank you

**Comment by pmenzel** [comment]
Hi,
make sure that you use the latest version of Kaiju and also that you make your database with Kaiju version > 1.5.0.
Otherwise the acc nr would not be in the database or not displayed properly.

**Comment by dovivi** [comment]
Oh, I see.. it's a new feature from last version, I was working with an old one, thank you!
