### ISSUE TITLE
Error when merging outputs from Kraken and Kaiju with -c option

### ISSUE THREAD

**Issue by a1204350** [bioinformatics-centre/kaiju#48]
command:
mergeOutputs -i 56Fnonhunman_kaiju_sort -j 56Fnonhunman_kraken.output_sort -v -c lowest -t /home/zong/programs_and_scripts/kaiju/nodes.dmp -o combined.out

terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)

merging succeeded with -c 1 and -c 2, but failed when using -c lowest and -c lca 

thanks

**Comment by pmenzel** [comment]
oww, sounds buggy. Could you send me the files (zipped) or  upload them somewhere? 
I assume you use the latest version of kaiju from github and a recent nodes.dmp file..?
thanks

**Comment by a1204350** [comment]
Files might be too large to be uploaded.
Both kraken and kaiju database are the latest ones.

**Comment by pmenzel** [comment]
If it crashes immediately upon processing, then you can also just send the first 1000 or so lines of each file. 
Also make sure, that both files have 3 tab separated columns with tax id in the 3rd column.

**Comment by a1204350** [comment]
The two files have been sent to your email. Cheers
