### ISSUE TITLE
Output only one taxon with kaijuReport

### ISSUE THREAD

**Issue by koopkaup** [bioinformatics-centre/kaiju#49]
This is a feature request to specify which taxon is shown with kaijuReport. For example only bacteria or archaea.

**Comment by pmenzel** [comment]
You can try this hack, put this in line 195 of kaijuReport.cpp and replace XXX with the NCBI taxon id of whatever taxon you want to retain, e.g. 2 for bacteria:
```
if(!is_ancestor(nodes,XXX,taxonid)) {
        continue;
 }
```
Then all lines with taxon ids not in the bacteria subtree are ignored
