### ISSUE TITLE
Wrong unclassified pct. value in report file

### ISSUE THREAD

**Issue by VGalata** [bioinformatics-centre/kaiju#5]
The percentage of the unclassified sequences seems to be wrong when using `kaijuReport`. E.g. the script reports 18.13% though there are 3888 of 17555 unclassified sequences, so 22.15% would be correct. Other percentage values seem to be calculated correctly.

**Edit**
Used version: release `1.4`

Version `1.4-6` reports **correct** percentage values.

**Comment by pmenzel** [comment]
Hi, do you have the latest version from GitHub? I fixed a bug regarding this in this [commit from 31/5](https://github.com/bioinformatics-centre/kaiju/commit/d764e51ec2f6fc7fec6153cfba1149d836da8edc)

**Comment by VGalata** [comment]
Hi!

You are right. Current version reports the correct percentage values. My post referred to the latest release and not the latest git version. Sorry!
