### ISSUE TITLE
KaijuReport not assigning viruses to any taxonomy rank

### ISSUE THREAD

**Issue by feargalr** [bioinformatics-centre/kaiju#50]
Hi, 

I'm having an issue when I run this that it isn't provide any classification rank in the KaijuReport function. The output will just say the following regardless of which taxonomic rank I use 

-------------------------------------------
46.769950          216000       Viruses
 2.405404           11109       cannot be assigned to a order
-------------------------------------------

Any idea why this is and how to fix it?

Thanks

**Comment by pmenzel** [comment]
Yeah reads matching to viruses at any rank are all put into the same bin.
I you need that information, it's probably easiest to make the Krona chart
and get the summarized numbers out from there.

**Comment by feargalr** [comment]
Thanks

**Comment by pmenzel** [comment]
The new program `kaiju2table` can expand all virus species when using option `-e`.
