### ISSUE TITLE
abundances

### ISSUE THREAD

**Issue by kengcher** [bioinformatics-centre/kaiju#54]
hi 

is there a way to convert the %mapped reads output to abundances?

**Comment by pmenzel** [comment]
Uhm, did you try the kaijuReport tool or use Kronatools?

**Comment by kengcher** [comment]
Hi yes I did use the kaijuReport tool. It prints out the number and percent
of reads mapped. Are we assuming %reads is the same as relative abundance?

Thank you.

On Nov 27, 2017 04:19, "Peter Menzel" <notifications@github.com> wrote:

Uhm, did you try the kaijuReport tool or use Kronatools?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bioinformatics-centre/kaiju/issues/54#issuecomment-347122322>,
or mute the thread

**Comment by pmenzel** [comment]
Yes, the percentage of classified reads for a taxon would be the equivalent of relative taxon abundance in this kind of analysis.

**Comment by kengcher** [comment]
Thank you Peter.
