### ISSUE TITLE
Assigning taxonomy to contigs using Kaiju

### ISSUE THREAD

**Issue by feargalr** [bioinformatics-centre/kaiju#55]
Hi, 

I was wondering is there any technical reasons why taxonomy could not be assigned to taxonomy using this approach, not for abundance estimates, but just for taxonomic assignment?
Thanks,
Feargal

**Comment by pmenzel** [comment]
Hi,

Technically, I think Kaiju should work well with contig sequences. If there are technical problems, then please tell me :)

However, on a conceptual level, Kaiju was made for classifying reads, which typically only cover one gene. Contigs are much longer and likely cover more than one gene, so in principle one could do a more sophisticated classification based on multiple matches and not rely only on the best matching sequence, as Kaiju is doing.

Peter

**Comment by feargalr** [comment]
Thanks!
