### ISSUE TITLE
Problem with intermediate ranks when creating report file

### ISSUE THREAD

**Issue by VGalata** [bioinformatics-centre/kaiju#6]
I am not sure whether that is a feature or a bug but `kaijuReport` includes intermediate ranks in the created report file resulting in percentage values whose sum is >100%.

Example: The full lineage of species *Acinetobacter baumannii* has *Acinetobacter calcoaceticus/baumannii complex* (species group). The report file (created for species rank) contains then *A. baumannii* (57.76%) **and** *A. calcoaceticus/baumannii complex* (52.67%).

It would be great if one could avoid that by using an additional parameter when calling `kaijuReport`.

**Edit 1**: Used version: `v1.4-6-gc547bc3`

**Edit 2**: Moreover, this issue affects the percentage and number of sequences classified above the given rank.

**Comment by pmenzel** [comment]
There was a bug when reading the nodes.dmp file and parsing the rank names, which should be fixed now with the latest commit. 

Would you please check that it works now for you?

**Comment by VGalata** [comment]
Seems to work. Thank you very much!
