### ISSUE TITLE
makeDB.sh error

### ISSUE THREAD

**Issue by PedroDaPos** [bioinformatics-centre/kaiju#62]
Dear Kaiju developer,
When running makeDb.sh -n - e , I have gotten the following error message:

```
11:17:20 Reading accession to taxon id map from file prot.accession2taxid
/rhome/prodrigues/bigdata/kaiju/bin/makeDB.sh: line 269: 14377 Broken pipe             gunzip -c nr.gz
     14404 Bus error               | convertNR -t nodes.dmp -g prot.accession2taxid -a -o kaiju_db_nr_euk.faa -l $SCRIPTDIR/taxonlist.tsv
```

I am wondering if you could help me finding a solution for this issue. Thank you in advance!

**Comment by pmenzel** [comment]
Hi,

that looks a bit like an issue with program reading data from the file system, but it's hard to tell.

Did the `nr.gz` download finish properly? The file should be around 34.8GB. You could try to extract it with `gunzip nr.gz` and see if that works properly.

**Comment by PedroDaPos** [comment]
Hi Peter,
Thank you for your quick reply, I appreciate!
I found out the possible culprit: I was running makeDB.sh in a cluster node that is limited in memory available for running jobs. I ran it again, in a different node and this time with more memory and cpus, and the job was completed successfully!

Thank you,

Pedro

**Comment by pmenzel** [comment]
Great!

Also, I suggest to have 60GB RAM available when running Kaiju using the NR+euk database.
