### ISSUE TITLE
Support reads compressed with bz2

### ISSUE THREAD

**Issue by johanneswerner** [bioinformatics-centre/kaiju#66]
I have a few big metagenome samples and due to their size, they are compressed with bzip2. 

Is it possible to support bz2 compression as well?

**Comment by pmenzel** [comment]
Kaiju includes the [zstr](https://github.com/mateidavid/zstr) for reading gzip-compressed files, but it cannot decompress bzip2. 

But regardless, if you use Linux and bash or zsh, you can use the process substitution operator of the shell to decompress bzip2 files on the fly, e.g
```
kaiju -i <(bzip2 -d -c reads.fastq.bz2) ...
```

**Comment by johanneswerner** [comment]
Okay, thank you.
