### ISSUE TITLE
which database to use

### ISSUE THREAD

**Issue by chloelulu** [bioinformatics-centre/kaiju#67]
Hi, 
I saw there are five database in Kaiju http://kaiju.binf.ku.dk/server
I plan to use Kaijun to analysis the shotgun metagenomics data with 100bp pair-ended reads(Hiseq). I am wondering which to use. I just want to classify bacteria and archaea. Confusing. 
I have used kraken, only 3% of the reads can got hits. So I want to try Kaiju, since as it published in the paper, which showed much more hits of reads for environmental samples.
Thanks in advanced.

**Comment by pmenzel** [comment]
Hi,
if you are just interested in bacteria and Archaea, then just use the "NCBI BLAST nr" database.
