### ISSUE TITLE
Custom db without NCBI taxon identifiers

### ISSUE THREAD

**Issue by adamclooney** [bioinformatics-centre/kaiju#68]
Hi there,

We wish to make a custom database to run with kaiju however the results are not taxonomy based and therefore we are unable to provide taxon identifiers from the NCBI. Is this possible?

Thank you!

**Comment by pmenzel** [comment]
Hi,
yes, you can make an custom database with amino acid sequences and then use the program kaijux (for nucleotide sequence queries) or kaijup (for amino acid sequence queries), see [here for instructions](https://github.com/bioinformatics-centre/kaiju#kaijux-and-kaijup).
