### ISSUE TITLE
Building multiple databases

### ISSUE THREAD

**Issue by samfux84** [bioinformatics-centre/kaiju#70]
Do the 4 databases need to be built in separate directories or can they also be built in the same directory ? This is not very clear from the description in the readme.

**Comment by pmenzel** [comment]
Only the NR and NR+euk databases get different file names (`kaiju_db_nr.fmi` and `kaiju_db_nr_euk.fmi`), while the Refseq, ProGenomes, and MAR databases are all named (`kaiju_db.fmi`). Therefore, I recommend to use different directories for each.

**Comment by samfux84** [comment]
Thank you for the quick reply.
