### ISSUE TITLE
Doc on alignment quality

### ISSUE THREAD

**Issue by TYMichaelsen** [bioinformatics-centre/kaiju#71]
Hi Peter,
Great (and fast!) software. However, I think it would be nice if kaiju could report a more simplistic score assesment in addition to the blosum62 score (GREEDY) or length of longest alignment (MEM). For example, the number of matches vs read length (i.e. the identity) would be useful information.

**Comment by pmenzel** [comment]
Hi,

while MEM mode does not have mismatches, the information about is mismatches is not carried along when processing the list of amino acid fragments in Greedy mode, so only the matching fragment sequence is shown when the output is printed. 

Anyways, I think the percentage identity between translated read and database sequence is not so useful. You could also use the E-value calculation and cutoff using option `-E`, if you want to account for read length in the match threshold and not only rely on BLOSUM scores or match length.

**Comment by pmenzel** [comment]
Yes, E-value depends on database length. I just suggested it because it sounded like you looked for another option of thresholding the output besides scores/length. I agree that PID can be useful for evaluating sequence divergence. :)

**Comment by TYMichaelsen** [comment]
Thanks for the reply, I have no further questions. Good day!
