### ISSUE TITLE
Add option not to extract genomes 

### ISSUE THREAD

**Issue by koopkaup** [bioinformatics-centre/kaiju#75]
Right now there is an option not to download data, but there should be also option to skip gbk2faa.pl command if you have already done it.

**Comment by pmenzel** [comment]
Hm maybe..  so you mean to skip all steps and jump directly to creating the BWT/FMI ?

**Comment by koopkaup** [comment]
Exactly. I had a scenario where I ran out of memory in the index file creating step and had to start over but as I had already downloaded and extracted all the genome files I wanted to skip that step.
