### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jarrodscott** [bioinformatics-centre/kaiju#79]
Hi I am using `Kaiju 1.6.2`

I had a small suggestion. In the help menu for `addTaxonNames` the `-r` flag states the following:

`Print taxon path containing only ranks specified by a comma-separated list,
                 for example: superkingdom,phylum,order,class,family,genus,species`

If a user follows this recipe `class` and `order` are transposed in the results but the headers for class & order are still in the proper order. Any chance you could change the flag to read `superkingdom,phylum,class,order,family,genus,species`

**Comment by pmenzel** [comment]
Thanks, I will have a look.
