### ISSUE TITLE
potential feature request - standalone LCA module

### ISSUE THREAD

**Issue by slhogle** [bioinformatics-centre/kaiju#80]
Hi Peter,

It would be super useful for me (and perhaps others) if there was a tool or module in the Kaiju family that given the names.dmp and nodes.dmp files would accept delimited taxonomy ids (from stdin or a file) and output the resulting LCA taxonomy id to stdout or file. 

so if there was a tsv file with lines like

`1946000\t1914538\t316\t306`

the new tool/module would output `1224`

I know there is a tool in krona to do this, but if you are using a custom database with custom taxonomy ids/ranks then it doesn't work with `ktGetLCA`

Since Kaiju performs this calculation on numerous occasions anyway, I thought the solution might be easily implemented. Is there a tool in Kaiju to do this already?

thanks for the help!
-shane

**Comment by pmenzel** [comment]
Hi,
yes that is something easy to implement. I already have a Perl script that does that with the NR fasta file.. I will check it..

Probably there are also some scripts floating around the web that do such a thing.

Peter

**Comment by slhogle** [comment]
ok great thank you!

**Comment by pmenzel** [comment]
Try [lca.cpp](https://gist.github.com/pmenzel/af5257fa272e3dddf3a369406c64de41). It reads a tsv file with NCBI taxon ids and prints the LCA using nodes.dmp. Compilation instructions are inside the file.

**Comment by slhogle** [comment]
thanks! this works perfectly for my needs

cheers,
-shane
