### ISSUE TITLE
Shared access to Kaiju DB via RAMDISK/TMPFS

### ISSUE THREAD

**Issue by your-highness** [bioinformatics-centre/kaiju#82]
Dear Kaiju devs,

For Kraken, a RAMDISK/TMPFS partition can be used to load the DB for shared access which is convenient when processing multiple samples at once. 

When starting Kaiju with a DB (*.fmi) on a TMPFS partion, the process loads the database again into process-local RAM. Can this re-loading be avoided (like the `--memory-mapping` switch in kraken2)?

Thanks in advance!

**Comment by pmenzel** [comment]
Hi,
I have no plan to implement shared memory right now. 

If you run the program in a loop with all the samples, then database loading becomes faster after the first runs.
