### ISSUE TITLE
kaiju.out.summary using kaiju webserver

### ISSUE THREAD

**Issue by gkong1** [bioinformatics-centre/kaiju#85]
Hi there, is there any way that I can create a kaiju.out.summary (and able to specify which rank to extract) from the outputs of kaiju webserver?
For example, something like this (at the genus level) would be really useful:

        %           reads       genus
-------------------------------------------
26.355562         1324367       Acidithiobacillus
13.232080          664912       Thermoproteus
11.305055          568079       Thiomonas
 1.762607           88571       Sulfolobus
-------------------------------------------
 0.515284           25893       Viruses
 5.868995          294917       classified above rank genus 
 9.373433          471015       belong to a genus with less than 1% of all reads
-------------------------------------------
31.586984         1587246       unclassified

Thanks in advance!

**Comment by pmenzel** [comment]
Hi,
this output is created by [kaijuReport](https://github.com/bioinformatics-centre/kaiju#creating-classification-summary).
You can download the names.dmp and nodes.dmp files from the NCBI FTP server or from the Kaiju web server: http://kaiju.binf.ku.dk/database/kaiju_index.tgz

**Comment by gkong1** [comment]
Hi, thanks for the reply. Just noticed that the indexes are available for download on the side. Tho is there a possibility that there is a web plugin version of kaijuReport? since the reason I am using the webserver NCBI BLAST nr +euk classification is because I do not have the resources to run it.

**Comment by pmenzel** [comment]
Yeah, maybe the web server should run kaijuReport on various ranks immediatly after it finishes the classification..
