### ISSUE TITLE
Viruses report is not deeply annotated than Bacteria.

### ISSUE THREAD

**Issue by okapick** [bioinformatics-centre/kaiju#86]
It is a example of kaijureport for families. but the same for genus, species...

The viruses are not classification. As you can see in the end of the report. But when i make the krona graph and addTaxonomy is worked. I can see the viruses family (specie,genus..) there. 

`        %	    reads	family
-------------------------------------------
 2.855948	     1912	Streptomycetaceae
 2.152417	     1441	Salpingoecidae
 1.778993	     1191	Flavobacteriaceae
 1.634104	     1094	Bacillaceae
 1.214375	      813	Pseudomonadaceae
 1.138197	      762	Burkholderiaceae
 1.090399	      730	Aspergillaceae
 0.963434	      645	Debaryomycetaceae
 0.933560	      625	Mycobacteriaceae
 0.921611	      617	Rhodobacteraceae
 0.894724	      599	Clostridiaceae
 0.891737	      597	Pseudonocardiaceae
 0.861863	      577	Plasmodiidae
 0.852901	      571	Paenibacillaceae
 0.806596	      540	Trypanosomatidae
 0.760292	      509	Vibrionaceae
 0.709506	      475	Enterobacteriaceae
 0.661708	      443	Lachnospiraceae
 0.640796	      429	Saprolegniaceae
 0.609428	      408	Saccharomycetaceae
 0.597479	      400	Nocardiaceae
 0.540718	      362	Herpotrichiellaceae
 0.521300	      349	Microbacteriaceae
 0.518313	      347	Micromonosporaceae
 0.507857	      340	Rhizobiaceae
 0.506363	      339	Neocallimastigaceae
 0.501882	      336	Sphingomonadaceae
 0.474996	      318	Comamonadaceae
 0.427197	      286	Mortierellaceae
 0.407779	      273	Sphingobacteriaceae
 0.397323	      266	Moraxellaceae
 0.385374	      258	Micrococcaceae
 0.385374	      258	Nectriaceae
 0.382386	      256	Sarcocystidae
 0.382386	      256	Ruminococcaceae
 0.373424	      250	Bradyrhizobiaceae
 0.371930	      249	Lactobacillaceae
 0.367449	      246	Acanthamoebidae
 0.362968	      243	Cunninghamellaceae
 0.361475	      242	Symbiodiniaceae
 0.355500	      238	Xanthomonadaceae
 0.348031	      233	Glomerellaceae
 0.328613	      220	Oxalobacteraceae
 0.325626	      218	Prevotellaceae
 0.321145	      215	Glomeraceae
 0.319651	      214	Dictyosteliaceae
 0.316664	      212	Rhodospirillaceae
 0.312183	      209	Streptococcaceae
 0.309195	      207	Acetobacteraceae
 0.303220	      203	Pucciniaceae
 0.300233	      201	Geminigeraceae
 0.289777	      194	Alteromonadaceae
 0.286790	      192	Chlamydomonadaceae
 0.286790	      192	Mycosphaerellaceae
 0.286790	      192	Reticulomyxidae
 0.285296	      191	Phyllobacteriaceae
 0.283802	      190	Cryptococcaceae
 0.280815	      188	Ustilaginaceae
 0.274840	      184	Acytosteliaceae
 0.270359	      181	Basidiobolaceae
 0.265878	      178	Apusomonadidae
 0.264384	      177	Alcaligenaceae
 0.264384	      177	Bacteroidaceae
 0.253928	      170	Campylobacteraceae
 0.252435	      169	Cytophagaceae
 0.249447	      167	Spizellomycetaceae
 0.247954	      166	Eimeriidae
 0.246460	      165	Legeriomycetaceae
 0.241979	      162	Legionellaceae
 0.238991	      160	Planctomycetaceae
 0.231523	      155	Mucoraceae
 0.227042	      152	Volvocaceae
 0.227042	      152	Halomonadaceae
 0.227042	      152	Mamiellaceae
 0.227042	      152	Chitinophagaceae
 0.225548	      151	Oxytrichidae
 0.219573	      147	Enterococcaceae
 0.218080	      146	Clavicipitaceae
 0.216586	      145	Tetrahymenidae
 0.209118	      140	Entamoebidae
 0.207624	      139	Oceanospirillaceae
 0.207624	      139	Cavenderiaceae

(...)
 0.001494	        1	Proteinivoraceae
 0.001494	        1	Cuniculiplasmataceae
 0.001494	        1	Mesoaciditogaceae
 0.001494	        1	Endomicrobiaceae
 0.001494	        1	Thermonemataceae
 0.001494	        1	Chamaesiphonaceae
 0.001494	        1	Nanopusillaceae
 0.001494	        1	Candidatus Desulfofervidaceae
 0.001494	        1	Micropepsaceae
 0.001494	        1	Notoacmeibacteraceae
-------------------------------------------
 0.890243	      596	Viruses
26.006752	    17411	cannot be assigned to a family 
-------------------------------------------
 0.004481	        3	unclassified`

**Comment by pmenzel** [comment]
Yes, this is intended behavior. Viruses are all lumped together in `kaijuReport`.

**Comment by okapick** [comment]
OK. Sir. :(

**Comment by pmenzel** [comment]
Thew new program `kaiju2table` can expand all virus species when using option `-e`.
