### ISSUE TITLE
convert_mar_to_kaiju.py not executable

### ISSUE THREAD

**Issue by rec3141** [bioinformatics-centre/kaiju#88]
I had to do chmod+x convert_mar_to_kaiju.py to get makeDB.sh to work on MacOS on the latest release

**Comment by pmenzel** [comment]
Thanks, is the problem on line 138 in makeDB.sh (with `command -v convert_mar_to_kaiju.py`) ?
That line is actually not really needed..

**Comment by rec3141** [comment]
I'm not sure, the error was "Error: convert_mar_to_kaiju.py not found in" $PATH, then I added it to my $PATH and got the error again, then I made it executable and it worked.

**Comment by pmenzel** [comment]
Yeah, that is this line. I just remove it.
