### ISSUE TITLE
Make error: ConsumerThread

### ISSUE THREAD

**Issue by evelienadri** [bioinformatics-centre/kaiju#90]
Hi, 
I've git cloned kaiju and I'm trying to make. System is Debian 7. I get the error message below. 
Thanks for your help.

> g++ -O3 -pthread -std=c++11 -DNDEBUG -I./include -I./include/ncbi-blast+ -c -o ConsumerThread.o ConsumerThread.cpp
ConsumerThread.cpp: In member function ‘void ConsumerThread::getAllFragmentsBits(const string&)’:
ConsumerThread.cpp:207:17: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:210:16: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:225:16: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:228:15: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:244:17: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:247:16: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:262:16: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:265:15: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp: In member function ‘Fragment* ConsumerThread::getNextFragment(unsigned int)’:
ConsumerThread.cpp:302:18: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:306:17: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:316:17: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:320:16: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp: In member function ‘void ConsumerThread::addAllMismatchVariantsAtPosSI(const Fragment*, unsigned int, size_t, SI*)’:
ConsumerThread.cpp:378:15: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp: In member function ‘void ConsumerThread::doWork()’:
ConsumerThread.cpp:673:18: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:677:17: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:689:17: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp:693:16: error: ‘class std::multimap<unsigned int, Fragment*, std::greater<unsigned int> >’ has no member named ‘emplace’
ConsumerThread.cpp: In member function ‘void ConsumerThread::ids_from_SI(SI*)’:
ConsumerThread.cpp:823:19: error: ‘class std::set<std::basic_string<char> >’ has no member named ‘emplace’
make: *** [ConsumerThread.o] Error 1

**Comment by pmenzel** [comment]
Hi, I didn't see this error before.. Seems like your C++ stdlib misses this function.. I am not sure.. Did you try to compile it on other machines?
You can also use the static binaries from here: https://github.com/bioinformatics-centre/kaiju/releases/download/v1.6.3/kaiju-1.6.3-linux-x86_64.tar.gz

**Comment by evelienadri** [comment]
The git clone worked on another machine. Since I didn't have root privileges, I used the static binaries provided and these worked. 
Thank you!
