### ISSUE TITLE
taxonlist.tsv in "bin" folder 

### ISSUE THREAD

**Issue by tseemann** [bioinformatics-centre/kaiju#93]
There is a taxonlist.tsv file which ends up installed into the `bin` folder.

Any chance this could be moved to another folder?

**Comment by pmenzel** [comment]
This file is needed by `makeDB.sh -e`. You can just remove it, if you don't use `-e`.

**Comment by tseemann** [comment]
Traditionally this file would be kept in your `etc` or `share` folder, and the makeDB script would access it from there.
