### ISSUE TITLE
Error - core dumped! 

### ISSUE THREAD

**Issue by antonioggsousa** [bioinformatics-centre/kaiju#95]
Hi, 
I'm running Kaiju on an Ubuntu 18.0 LTS system, with 4 cores and 16 Gb RAM. 

I have installed Kaiju successfully, and then due to limited RAM memory, I downloaded the Mar databases, with `makeDB.sh -m`. Although, the documentation says that we need two files 'nodes.dmp' and other with the '.fmi' extension, I just got the first, and the closest match with the second was the file 'mkfmi'. 

When I tried to run Kaiju, i got the following error: 

`./kaiju -t nodes.dmp -f mkfmi -i 1_orf.nucl.fasta -z4 -o 1_metaTAX.tab
Segmentation fault (core dumped)`

I do not know if the error arose due to the wrong database or other issue. 
I hope that someone can help on this!
Thanks in advance. 
Cheers, 
António

**Comment by pmenzel** [comment]
Hi,
The `-f` option needs the kaiju index file (e.g. `kaiju_db.fmi`) as argument.
If `makeDB.sh` didn't produce that file, then something went wrong, e.g. too little available RAM.

**Comment by antonioggsousa** [comment]
Thank you @pmenzel and sorry for the late reply. 

I tried to run script by script, i.e., I open the make.sh file and I run script by script related with the Mar databases, and it worked, i.e., it generated the nodes.dmp and kaiju_db.fmi files. 

Thank you @pmenzel!
