### ISSUE TITLE
How to submit multiple files

### ISSUE THREAD

**Issue by lmanchon** [bioinformatics-centre/kaiju#96]
--Hi all,

i have to submit 80 paired-end files (2x150bp fastq.gz). How to do this ? I think your web server submission form accept only 1 paired-end file, don't you ? If not how to do ?

thank you --

**Comment by pmenzel** [comment]
Hi,
you can only upload one file (or two files for paired-end) in parallel.
For 80 files, it is best to just run kaiju locally.

**Comment by lmanchon** [comment]
Ok, but then how can i do to merge together each output per sample ?

**Comment by pmenzel** [comment]
This can be done using the `kaiju2table` program, see README.md
